# Build stage
FROM python:3.12-slim AS builder

WORKDIR /build

# Use Aliyun mirror for faster downloads in China
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip config set global.trusted-host mirrors.aliyun.com

# Install build dependencies
COPY pyproject.toml ./
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Install project dependencies ONLY (layer cached unless pyproject.toml changes).
# 不 build llm-test 包本身(需要源码,会让缓存随每次代码改动失效)——只解析 pyproject.toml
# 的 dependencies 列表装第三方包。源码在 runtime 阶段 COPY,用 PYTHONPATH=/app import。
RUN python -c "import tomllib; deps=tomllib.load(open('pyproject.toml','rb'))['project']['dependencies']; open('/tmp/deps.txt','w').write('\n'.join(deps))" \
    && pip install --no-cache-dir -r /tmp/deps.txt \
    && rm /tmp/deps.txt


# App-code stage: flatten the repo WITHOUT the tokenizer bundle so the runtime
# image carries the bundle exactly once (at /app/tokenizers, not duplicated).
FROM python:3.12-slim AS app-code
WORKDIR /app
COPY . .
RUN rm -rf tokenizers tokenizers_bundle


# Runtime stage
FROM python:3.12-slim

WORKDIR /app

# docker CLI 在运行时从宿主机挂载(只读,见 compose volumes),无需 apt 安装。
# docker 只依赖 libc,挂载宿主机 /usr/bin/docker 即可在容器内 docker inspect/logs。

# Copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy application code (bundle already excluded above)
COPY --from=app-code /app/ /app/

# Self-contained tokenizers for offline deployment.
# Generated by `python scripts/prepare_tokenizers.py` before building.
COPY tokenizers_bundle/ /app/tokenizers/

# Ensure /app is importable (replaces editable install)
ENV PYTHONPATH=/app

# Create data directories
RUN mkdir -p data datasets cache api_logs presets results

EXPOSE 8501

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8501/_stcore/health')" || exit 1

ENTRYPOINT ["streamlit", "run", "app.py"]
