"""
Phase 4: Deep file-specific translation targeting all remaining Chinese in UI files.
This script uses precise, long-phrase-first replacements specific to each file.
"""
import re
import os


def translate_file(filepath, replacements):
    """Apply replacements to a file, longest-first."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except:
        return -1
    
    original = content
    # Sort by length (longest first) to avoid partial match issues
    sorted_reps = sorted(replacements, key=lambda x: -len(x[0]))
    for old, new in sorted_reps:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        remaining = len(re.findall(r'[\u4e00-\u9fff]+', content))
        return remaining
    return -1


# =====================================================================
# FILE: ui/charts.py
# =====================================================================
CHARTS = [
    ('1decimal places', '1 decimal place'),
    ('2decimal places', '2 decimal places'),
    ('移除硬件/Model信息子标题，保持界面整洁', 'removed hardware/model info subtitle for clean UI'),
    ('基准颜色', 'base color'),
    ('Display数值Label', 'Display value labels'),
    ('AddRelative Perf视图', 'Add relative performance view'),
    ('Relative Perf视图目前Not supported多条线', 'Relative perf view currently does not support multiple lines'),
    ('Add二条Relative Perf线', 'Add secondary relative performance line'),
    ('动态Sety轴范围', 'Dynamically set Y-axis range'),
    ('useSmart formatting', 'Use smart formatting'),
    ('Bold values，Smart formatting', 'Bold values, smart formatting'),
    ('Simulate static chart\"hollow/bullseye\"effect: white fill + thick color border', 'Simulate static chart hollow/bullseye effect: white fill + thick colored border'),
    ('专门用于DisplayRelative PerfBar Chart', 'Dedicated bar chart for displaying relative performance comparison'),
    ('Relative Perf对比', 'Relative Performance Comparison'),
    ('AddRelative PerfBar Chart（深色）', 'Add relative performance bar chart (dark color)'),
    ('Relative Perf图表失败', 'Relative performance chart failed'),
]

# =====================================================================
# FILE: ui/onboarding.py
# =====================================================================
ONBOARDING = [
    # ONBOARDING_CONTENT - welcome
    ('👋 Welcome to LLM 基准Test平台', '👋 Welcome to the LLM Benchmark Platform'),
    ('这is一专业 LLM 性能Test工具', 'This is a professional LLM performance testing tool'),
    ('**主要功能：**', '**Main Features:**'),
    ('TestModelinnot同Concurrency级别under性能表现', 'Test model performance at different concurrency levels'),
    ('评估ModelProcess长输入能力', 'Evaluate model long input processing capability'),
    ('TestModelin长onunder文场景under表现', 'Test model performance in long context scenarios'),
    ('多维度全面评估Model性能', 'Multi-dimensional comprehensive model evaluation'),
    ('综合Test', 'Matrix Test'),
    ('useCustom文本进行Test', 'Test using custom text'),
    ('CustomTest', 'Custom Test'),
    ('一键运行所hasTest Type', 'Run all test types with one click'),
    ('**Test指标：**', '**Test Metrics:**'),
    ('首tokenLatency', 'First token latency'),
    ('Token use', 'Token usage'),
    ('输入/输出 token Statistics', 'Input/output token statistics'),
    ('总耗时', 'Total duration'),
    ('完整请求耗时', 'Complete request duration'),
    ('您can随时in侧边栏重新打开此引导', 'You can reopen this guide anytime from the sidebar'),
    ('Test Resultswill自动Save，可inHistoryin查看', 'Test results are automatically saved and can be viewed in History'),
    # api_config
    ('Configure您 API Connect信息', 'Configure your API connection'),
    ('in左侧侧边栏in：', 'In the left sidebar:'),
    ('选择 API Provider', 'Select API Provider'),
    ('orother兼容Provider', 'or other compatible providers'),
    ('填写 API 信息', 'Fill in API information'),
    ('API 端点地址', 'API endpoint address'),
    ('要TestModel name', 'Model name to test'),
    ('您 API 密钥', 'Your API key'),
    ('Configure Tokenizer', 'Configure Tokenizer'),
    ('选择 HuggingFace Tokenizer 进行精确计数', 'Select HuggingFace Tokenizer for precise counting'),
    ('oruse API Return token 计数', 'or use API-returned token counts'),
    ('安全Tip：', 'Security tips:'),
    ('API Key 仅存储in本地will话in，notwillon传', 'API Key is only stored in local session, never uploaded'),
    ('Suggestionuse受限 API Key 进行Test', 'Recommend using a restricted API Key for testing'),
    ("点击 'GetModel列表' 可Validate API Connect", "Click 'Get Model List' to validate API connection"),
    ('常用Configure可Saveis预设，方便under次use', 'Common configurations can be saved as presets for future use'),
    # test_selection
    ('Select Test类型', 'Select Test Type'),
    ('选择要运行Test', 'Choose the test to run'),
    ('Test TypeDescription:', 'Test Type Description:'),
    ('说明', 'Description'),
    ('适用场景', 'Use Case'),
    ('Testnot同Concurrency级别性能', 'Test performance at different concurrency levels'),
    ('评估ConcurrencyProcess能力', 'Evaluate concurrency processing capability'),
    ('Test长输入Process能力', 'Test long input processing capability'),
    ('评估 Prefill 性能', 'Evaluate prefill performance'),
    ('Test长onunder文Process', 'Test long context processing'),
    ('评估长文本理解能力', 'Evaluate long text comprehension'),
    ('Concurrency+onunder文组合Test', 'Concurrency + context combination test'),
    ('全面性能评估', 'Comprehensive performance evaluation'),
    ('useCustom文本', 'Use custom text'),
    ('特定场景Test', 'Specific scenario test'),
    ('参数Configure：', 'Parameter Configuration:'),
    ('同时发送请求数量', 'Number of simultaneous requests'),
    ('最大Generate token 数', 'Maximum generated tokens'),
    ('温度: 控制输出随机性', 'Temperature: controls output randomness'),
    ('Thinking mode: 启用Model推理能力', 'Thinking mode: enable model reasoning'),
    ('初次useSuggestion从 \'快速Test\' 预设开始', 'First-time users should start with the \'Quick Test\' preset'),
    ('压力Testwill消耗更多 API 配额', 'Stress tests consume more API quota'),
    # run_test
    ('启动Test', 'Start Test'),
    ('in统一Test控制面板in：', 'In the unified test control panel:'),
    ('ConfirmConfigure', 'Confirm configuration'),
    ('查看Configure摘要确保参数正确', 'Review configuration summary to ensure correct parameters'),
    ("点击 '🚀 启动Test' 按钮", "Click the '🚀 Start Test' button"),
    ('监控进度', 'Monitor progress'),
    ('实时查看Test进度andStatus', 'View test progress and status in real-time'),
    ('Test控制：', 'Test control:'),
    ('in断Current Test', 'Interrupt current test'),
    ('Restore', 'Resume'),
    ('从on次停止处继续', 'Continue from where it was stopped'),
    ('Real-time Monitoring：', 'Real-time Monitoring:'),
    ('进度条DisplayCurrent Test进度', 'Progress bar shows current test progress'),
    ('Real-time loggingDisplay每 requestsStatus', 'Real-time logs show status of each request'),
    ('动态图表DisplayPerformance Metrics', 'Dynamic charts display performance metrics'),
    ('Test过程in可随时停止，SavedResultnotwill丢失', 'You can stop the test anytime without losing saved results'),
    ('Suggestion先运行小规模TestValidateConfigure', 'Recommend running a small test first to validate configuration'),
    # results
    ('分析Test Results', 'Analyze Test Results'),
    ('Result展示：', 'Results Display:'),
    ('Data表格', 'Data Table'),
    ('详细Test ResultsData', 'Detailed test results data'),
    ('支持Sortand筛选', 'Supports sorting and filtering'),
    ('可Export as CSV 文件', 'Can be exported as CSV file'),
    ('Visualization图表', 'Visualization Charts'),
    ('性能Trend Chart', 'Performance trend charts'),
    ('Concurrency性能对比', 'Concurrency performance comparison'),
    ('Token use分布', 'Token usage distribution'),
    ('Test Report', 'Test Report'),
    ('自动Generate性能分析报告', 'Automatically generates performance analysis reports'),
    ('包含关键指标解读', 'Includes key metrics interpretation'),
    ('可Export as Markdown', 'Can be exported as Markdown'),
    ('Result对比', 'Result Comparison'),
    ('比较not同Model性能', 'Compare different model performances'),
    ('比较not同Configure效果', 'Compare different configuration effects'),
    ('useResult对比功能可直观比较多次Test', 'Use result comparison to visually compare multiple tests'),
    ('Historywill自动Savein items目in', 'History is automatically saved in the project directory'),
    # complete
    ('🎉 恭喜！', '🎉 Congratulations!'),
    ('您CompletedOnboarding！', 'You have completed the onboarding!'),
    ('您already学will：', 'You have learned:'),
    ('查看andAnalyze results', 'View and analyze results'),
    ('Next：', 'Next:'),
    ('尝试not同Test Configuration', 'Try different test configurations'),
    ('Save您常用Configureis预设', 'Save your common configurations as presets'),
    ('比较not同Model性能', 'Compare different model performances'),
    ('深入分析Test Results', 'Deep dive into test results'),
    ('needHelp？', 'Need help?'),
    ('点击侧边栏Help图标可随时重新查看本引导', 'Click the sidebar help icon to reopen this guide anytime'),
    ('查看 items目 README Get更多信息', 'Check the project README for more information'),
    ('祝您Test愉快！', 'Happy testing!'),
    ('收藏常用Configure可大幅提高Test效率', 'Saving common configurations can significantly improve testing efficiency'),
    # UI components
    ('引导内容', 'Onboarding Content'),
    ('引导界面组件', 'Onboarding UI Components'),
    ('Render引导弹窗', 'Render onboarding modal'),
    ('Create弹窗', 'Create modal'),
    ('进度条', 'Progress bar'),
    ('当前Step内容', 'Current step content'),
    ('标题and内容', 'Title and content'),
    ('导航按钮', 'Navigation buttons'),
    ('完成 ✅', 'Done ✅'),
    ('Render引导Trigger器（侧边栏）', 'Render onboarding trigger (sidebar)'),
    ('DisplayTrigger按钮', 'Display trigger button'),
    ('Reset引导Status', 'Reset onboarding state'),
    ('Render快速参考卡片', 'Render quick reference card'),
    ('in左侧Configure API', 'Configure API on the left'),
    ('查看Analyze results', 'View and analyze results'),
    ('详细Help', 'detailed help'),
    ('Render功能亮点', 'Render feature highlights'),
    ('功能亮点', 'Feature Highlights'),
    ('精确Test', 'Precise Testing'),
    ('支持 7 种Test Type', 'Supports 7 test types'),
    ('多维度Performance Metrics', 'Multi-dimensional performance metrics'),
    ('可复现Test Environment', 'Reproducible test environment'),
    ('深度分析', 'Deep Analysis'),
    ('实时进度监控', 'Real-time progress monitoring'),
    ('Visualization图表展示', 'Visualization chart display'),
    ('自动Generate报告', 'Automatic report generation'),
    ('智能管理', 'Smart Management'),
    ('Config PresetsSave', 'Configuration preset saving'),
    ('Test进度持久化', 'Test progress persistence'),
    ('HistoryQuery', 'History query'),
    ('灵活Configure', 'Flexible Configuration'),
    ('多 API Provider支持', 'Multi API provider support'),
    ('CustomTest Parameters', 'Custom test parameters'),
    ('Thinking modeTest', 'Thinking mode testing'),
    ('RenderFAQ', 'Render FAQ'),
    # FAQs
    ('如何选择合适Concurrency？', 'How to choose the right concurrency?'),
    ('Suggestion从小Concurrency开始：', 'Recommended to start with low concurrency:'),
    ('快速Test', 'Quick test'),
    ('标准Test', 'Standard test'),
    ('压力Test', 'Stress test'),
    ('Note:高Concurrencywill消耗更多 API 配额。', 'Note: High concurrency consumes more API quota.'),
    ('Test failed怎么办？', 'What to do when tests fail?'),
    ('常见原因and解决方法：', 'Common causes and solutions:'),
    ('Check API Key is否正确', 'Check if API Key is correct'),
    ('降低Concurrencyor稍后重试', 'Lower concurrency or retry later'),
    ('Check网络and API URL', 'Check network and API URL'),
    ('增加 max_tokens or降低Concurrency', 'Increase max_tokens or lower concurrency'),
    ('如何比较not同Model性能？', 'How to compare different model performances?'),
    ('useResult对比功能：', 'Use the result comparison feature:'),
    ('运行多 modelsTest', 'Run tests on multiple models'),
    ('inResult对比页面选择要比较Result', 'Select results to compare on the comparison page'),
    ('查看对比图表and报告', 'View comparison charts and reports'),
    ('test dataSavein哪里？', 'Where is test data saved?'),
    ('Test ResultsSavein：', 'Test results are saved in:'),
    ('test data', 'Test data'),
    ('Test进度', 'Test progress'),
    ('Config Presets', 'Configuration presets'),
    ('这些文件in items目目录under，您can安全地BackuporDelete。', 'These files are in the project directory and can be safely backed up or deleted.'),
    # Helper functions
    ('便捷函数', 'Helper Functions'),
    ('Display引导（if未完成）', 'Display onboarding (if not completed)'),
    ('Reset引导Status', 'Reset onboarding state'),
    ('Checkis否完成引导', 'Check if onboarding is completed'),
    ('Get当前Step名称', 'Get current step name'),
    ('Get引导进度', 'Get onboarding progress'),
    ('Initialize引导Status', 'Initialize onboarding state'),
    ('Checkis否Completed引导', 'Check if onboarding is completed'),
]

# =====================================================================
# FILE: ui/test_control_panel.py  
# =====================================================================
CONTROL_PANEL = [
    ('TestStatus常量', 'Test status constants'),
    ('失败', 'Failed'),
    ('Test Configuration类', 'Test Configuration Class'),
    ('Test ConfigurationData类', 'Test configuration data class'),
    ('Convertis字典', 'Convert to dictionary'),
    ('从字典Create', 'Create from dictionary'),
    ('从 session_state CreateConfigure', 'Create configuration from session_state'),
    ('Test Progress类', 'Test Progress Class'),
    ('Test Progress跟踪类', 'Test progress tracking class'),
    ('Get进度百分比', 'Get progress percentage'),
    ('GetElapsed Time（seconds）', 'Get elapsed time (seconds)'),
    ('估算Remaining时间（seconds）', 'Estimate remaining time (seconds)'),
    ('进度持久化管理器', 'Progress Persistence Manager'),
    ('Test Progress持久化管理器', 'Test progress persistence manager'),
    ('SaveTest Progress到文件', 'Save test progress to file'),
    ('Save进度失败', 'Failed to save progress'),
    ('从文件LoadTest Progress', 'Load test progress from file'),
    ('Load进度失败', 'Failed to load progress'),
    ('列出所hasSaved进度', 'List all saved progress'),
    ('未知', 'Unknown'),
    ('DeleteSaved进度', 'Delete saved progress'),
    ('Delete进度失败', 'Failed to delete progress'),
    ('清除旧进度文件', 'Clear old progress files'),
    ('全局进度管理器实例', 'Global progress manager instance'),
    ('统一Test控制面板组件', 'Unified Test Control Panel Components'),
    ('Render统一Test控制面板', 'Render unified test control panel'),
    ('这is一集in化Test控制界面，提供：', 'This is a centralized test control interface providing:'),
    ('Test Type选择', 'Test type selection'),
    ('Configure摘要Display', 'Configuration summary display'),
    ('Test控制按钮（开始/暂停/继续/停止）', 'Test control buttons (start/pause/resume/stop)'),
    ('进度监控', 'Progress monitoring'),
    ('可Resume Test列表', 'Resumable test list'),
    ('Create两列布局：左侧控制，右侧Status', 'Create two-column layout: left for control, right for status'),
    ('Test控制', 'Test Control'),
    ('Test类型选择', 'Test type selection'),
    ('选择Test Type', 'Select test type'),
    ('Config摘要', 'Configuration summary'),
    ('Configure摘要', 'Configuration Summary'),
    ('Display关键Configure', 'Display key configuration'),
    ('温度', 'Temperature'),
    ('Thinking mode: ✅ (预算:', 'Thinking mode: ✅ (budget:'),
    ('GetCurrent Status', 'Get current status'),
    ('控制按钮组 - 4按钮：开始、暂停、继续、停止', 'Control button group - 4 buttons: start, pause, resume, stop'),
    ('开始按钮：Idle时可用', 'Start button: available when idle'),
    ('开始', 'Start'),
    ('暂停按钮：仅运行时可用', 'Pause button: only available while running'),
    ('暂停', 'Pause'),
    ('currentlyPause Test...', 'Pausing test...'),
    ('继续按钮：仅暂停时可用', 'Resume button: only available when paused'),
    ('继续', 'Resume'),
    ('停止按钮：运行or暂停时可用', 'Stop button: available while running or paused'),
    ('停止', 'Stop'),
    ('currentlyStop Test...', 'Stopping test...'),
    ('Current StatusDisplay', 'Current status display'),
    ('Status颜色映射', 'Status color mapping'),
    ('Current TestStatus', 'Current test status'),
    ('进度:', 'Progress:'),
    ('时间信息', 'Time information'),
    ('已用:', 'Elapsed:'),
    ('预计Remaining:', 'Est. remaining:'),
    ('ErrorDisplay', 'Error display'),
    ('Render进度历史面板', 'Render progress history panel'),
    ('暂noSaveTest Progress', 'No saved test progress'),
    ('Delete此进度', 'Delete this progress'),
    ('Save时间:', 'Save time:'),
    ('Render可RestoreTest面板', 'Render resumable test panel'),
    ('Display所hasStatusis PAUSED or CANCELLED Test，允许用户Restore执行', 'Display all paused or cancelled tests, allowing users to resume'),
    ('Filter出可RestoreTest', 'Filter resumable tests'),
    ('可RestoreTest', 'Resumable Tests'),
    ('以underTestcanRestore执行：', 'The following tests can be resumed:'),
    ('Format时间Display', 'Format time display'),
    ('Save当前Test Progress', 'Save current test progress'),
    ('LoadSavedTest Progress', 'Load saved test progress'),
    ('清除当前进度', 'Clear current progress'),
    ('Get指定类型Test Configuration', 'Get test configuration for specified type'),
    ('LoadRestoreData', 'Load resume data'),
    ('包含RestoreData字典，ifLoad failedReturn None', 'Dictionary containing resume data, returns None if load failed'),
    ('Set session_state inRestore标志', 'Set resume flag in session_state'),
    ('LoadRestoreData失败', 'Failed to load resume data'),
    ('从进度Data准备Restore参数', 'Prepare resume parameters from progress data'),
    ('进度Data字典', 'Progress data dictionary'),
    ('Restore参数字典', 'Resume parameters dictionary'),
    ('seconds', 's'),
    ('minutes', 'min'),
    ('hours', 'hr'),
]

# =====================================================================
# FILE: ui/static_chart_generator.py
# =====================================================================
STATIC_CHART = [
    ('Static Chart Generator - 静态图表Generate器', 'Static Chart Generator'),
    ('借鉴 llm-performance-test.html  Canvas 画图风格，', 'Inspired by llm-performance-test.html Canvas drawing style,'),
    ('use Matplotlib Generate美观静态性能Test Results图片。', 'uses Matplotlib to generate beautiful static performance test result images.'),
    ('特点：', 'Features:'),
    ('干净白色背景 + Grid线', 'Clean white background + grid lines'),
    ('带阴影圆形Data点', 'Circular data points with shadow'),
    ('Data点on方Display数值Label', 'Data value labels displayed above data points'),
    ('平滑折线', 'Smooth line chart'),
    ('可Exportis静态 PNG 图片', 'Can be exported as static PNG images'),
    ('配色方案', 'Color Scheme'),
    ('青绿色 - 预Pad速度', 'Teal - Prefill speed'),
    ('粉红色 - 输出速度', 'Pink - Output speed'),
    ('蓝色 - TTFT', 'Blue - TTFT'),
    ('紫色 - Throughput', 'Purple - Throughput'),
    ('橙色 - TPS', 'Orange - TPS'),
    ('绿色 - Success Rate', 'Green - Success rate'),
    ('主色调 - 蓝色', 'Primary - Blue'),
    ('次要 - 灰色', 'Secondary - Gray'),
    ('Grid线颜色', 'Grid line color'),
    ('Axis颜色', 'Axis color'),
    ('文本颜色', 'Text color'),
    ('背景颜色', 'Background color'),
    ('字体Configure', 'Font Configuration'),
    ('智能数值Format', 'Smart Value Formatting'),
    ('智能Format数值，based on数值大小自动选择合适小数位数。', 'Smart format value, automatically selects appropriate decimal places based on value magnitude.'),
    ('规则：', 'Rules:'),
    ('保留整数 (0 位小数)', 'Integer (0 decimal places)'),
    ('保留 1 位小数', '1 decimal place'),
    ('保留 2 位小数', '2 decimal places'),
    ('要Format数值', 'Value to format'),
    ('该列/系列最大值，用于决定格式。ifis None，则use value 本身。', 'Max value of column/series for format decision. If None, uses value itself.'),
    ('Format后字符串', 'Formatted string'),
    ('Return一 matplotlib 兼容Format函数，用于 Y 轴刻度。', 'Returns a matplotlib-compatible format function for Y-axis ticks.'),
    ('该轴最大值', 'Max value of this axis'),
    ('Format函数', 'Format function'),
    ('静态图表Generate器，Create美观性能Test Results图表', 'Static chart generator for creating beautiful performance test result charts'),
    ('Initialize图表Generate器', 'Initialize chart generator'),
    ('图片分辨率', 'Image resolution'),
    ('Configure matplotlib 全局Set', 'Configure matplotlib global settings'),
    ('Get大于etc.于 max 最接近整数量级', 'Get the nearest nice round number >= max'),
    ('(如 1、2、5、10、20、50、100、200、500、1000 etc.)', '(e.g., 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000 etc.)'),
    ('最大值', 'Maximum value'),
    ('规范化最大值', 'Normalized maximum value'),
    ('绘制单Line Chart，支持系统信息Display', 'Draw single line chart with system info display'),
    ('顶部标题', 'Top title'),
    ('绘制系统信息（if提供）', 'Draw system info (if provided)'),
    ('绘制图表', 'Draw chart'),
    ('useetc.宽类别型 X 轴：用Index作is实际绘图位置', 'Use equal-width categorical X-axis: use index as actual plot position'),
    ('从1开始，留出0位置', 'Start from 1, leave room for 0 position'),
    ('Calculate Y 轴范围', 'Calculate Y-axis range'),
    ('X 轴刻度：0 + 实际DataLabel', 'X-axis ticks: 0 + actual data labels'),
    ('SetAxis范围', 'Set axis range'),
    ('留出右侧空间给 X 轴Label', 'Leave right space for X-axis labels'),
    ('绘制Grid线', 'Draw grid lines'),
    ('Grid线inDataunder方', 'Grid lines below data'),
    ('SetAxis样式', 'Set axis style'),
    ('绘制折线', 'Draw lines'),
    ('绘制Data点 - use scatter（避免Axis纵横比问题）', 'Draw data points using scatter (avoids axis aspect ratio issues)'),
    ('外圈：白色Pad，彩色边框', 'Outer ring: white fill, colored border'),
    ('内圈：实心', 'Inner ring: solid fill'),
    ('Data点数值Label', 'Data point value labels'),
    ('Set标题', 'Set title'),
    ('标题已in顶部统一绘制，此处no需 set_title', 'Title already drawn at top, no need for set_title here'),
    ('Set轴Label - Y 轴Label', 'Set axis label - Y-axis label'),
    ('智能Process X 轴刻度Label，防止重叠', 'Smart process X-axis tick labels to prevent overlap'),
    ('use set_xlabel Add X 轴Label', 'Use set_xlabel to add X-axis label'),
    ('Format Y 轴刻度Label', 'Format Y-axis tick labels'),
    ('增加高度', 'Increase height'),
    ('绘制双Line Chart（onunder排列），支持系统信息Display', 'Draw dual line chart (stacked vertically) with system info display'),
    ('增加高度以容纳信息', 'Increase height to accommodate info'),
    ('default图表起始高度稍微降低，防止大标题重叠', 'Default chart start height slightly lowered to prevent title overlap'),
    ('if标题包含换行符（长标题），且没has系统信息，也要under移动一点', 'If title contains newline (long title) and no system info, move down a bit'),
    ('动态Calculate图表高度and位置，确保in间has足够间距', 'Dynamically calculate chart height and position with sufficient spacing'),
    ('增加in间间距，防止 X 轴Labelandunder方标题重叠', 'Increase spacing to prevent X-axis labels overlapping with the bottom title'),
    ('可用总高度 = 顶部起始位置 - 底部边距 - in间间隙', 'Available height = top start - bottom margin - inter-chart gap'),
    ('绘制图表 1 (Top)', 'Draw chart 1 (Top)'),
    ('绘制图表 2 (Bottom)', 'Draw chart 2 (Bottom)'),
    ('in给定 Axes on绘制单Line Chart（useetc.宽类别型 X 轴）', 'Draw single line chart on given Axes (equal-width categorical X-axis)'),
    ('确保 y_data 都is数值', 'Ensure all y_data are numeric'),
    ('Process X 轴Label', 'Process X-axis labels'),
    ('Note:对于Concurrencyetc.非0起始Data，视觉on保留0点作is原点is很好风格', 'Note: for concurrency etc. non-zero starting data, keeping 0 as origin is good visual style'),
    ('绘制Data点 - use scatter', 'Draw data points using scatter'),
    ('Data点大小based on画布宽度动态调整，防止过密', 'Data point size dynamically adjusted based on canvas width to prevent crowding'),
    ('if点很多，适当缩小点大小', 'If many points, reduce point size'),
    ('Data点数值Label（避免重叠）', 'Data point value labels (prevent overlap)'),
    ('if点很多，can隔Display，or者只Display最大/最小值', 'If many points, display every other or only max/min values'),
    ('简单抽样', 'Simple sampling'),
    ('based onData点数量andLabel长度综合决定is否抽样Display刻度', 'Determine tick sampling based on data point count and label length'),
    ('估算每Label占用字符宽度（考虑字号），判断is否need抽样', 'Estimate character width per label, determine if sampling needed'),
    ('经验公式：当 n_points * max_label_len > 阈值时，Labelwill重叠', 'Empirical formula: when n_points * max_label_len > threshold, labels will overlap'),
    ('based onLabel长度动态Calculate最多Display多少刻度', 'Dynamically calculate max visible ticks based on label length'),
    ('6位数Label最多Display6', '6-digit labels show max 6'),
    ('5位数Label最多Display8', '5-digit labels show max 8'),
    ('始终包含一点', 'Always include first point'),
    ('始终包含最后一点', 'Always include last point'),
    ('只Display抽样后刻度', 'Only display sampled ticks'),
    ('加on原点 0', 'Add origin 0'),
    ('Label防重叠：ifLabel数量多or文本长，进行旋转', 'Label anti-overlap: rotate if many labels or long text'),
    ('旋转角度based onLabel长度and点数综合决定', 'Rotation angle determined by label length and point count'),
    ('use set_xlabel Add X 轴Label，利用 matplotlib 自动避免与刻度Label重叠', 'Use set_xlabel to add X-axis label, leveraging matplotlib auto-avoidance of tick label overlap'),
    ('Create完整性能Test Report图片', 'Create complete performance test report image'),
    ('包含：标题、系统信息、预Pad速度图、输出速度图', 'Contains: title, system info, prefill speed chart, output speed chart'),
    ('Test Results列表，每 items包含 input_length, prefill_speed, output_speed', 'Test results list, each item contains input_length, prefill_speed, output_speed'),
    ('系统信息字典，包含 processor, mainboard, memory, gpu, system, engine_name, model_name', 'System info dict containing processor, mainboard, memory, gpu, system, engine_name, model_name'),
    ('Test时间', 'Test time'),
    ('图像尺寸', 'Image size'),
    ('matplotlib Figure 对象', 'matplotlib Figure object'),
    ('提取Data', 'Extract data'),
    ('Create画布', 'Create canvas'),
    ('Add标题区域', 'Add title area'),
    ('Add大标题', 'Add main title'),
    ('本地大语言Model推理性能Test Results', 'Local LLM Inference Performance Test Results'),
    ('Add系统信息区域', 'Add system info area'),
    ('Restore到顶部布局，位于标题under方', 'Restore to top layout, below title'),
    ('Build信息列表，只包含has效信息', 'Build info list containing only valid info'),
    ('Process器', 'Processor'),
    ('主板', 'Mainboard'),
    ('内存', 'Memory'),
    ('显卡', 'GPU'),
    ('系统', 'System'),
    ('引擎名称', 'Engine Name'),
    ('Model name', 'Model Name'),
    ('动态布局：based onhas效信息数量决定每列行数', 'Dynamic layout: determine rows per column based on valid info count'),
    ('Add预Pad速度图', 'Add prefill speed chart'),
    ('图表under移，留出顶部空间', 'Move chart down, leave space at top'),
    ('预Pad速度', 'Prefill Speed'),
    ('输入长度', 'Input Length'),
    ('Add输出速度图', 'Add output speed chart'),
    ('输出速度', 'Output Speed'),
    ('统一绘制系统信息到 figure 顶部区域。', 'Draw system info uniformly at the top of the figure.'),
    ('系统信息字典', 'System info dictionary'),
    ('当前图表顶部位置', 'Current chart top position'),
    ('Update后 chart_top（under移后）', 'Updated chart_top (after moving down)'),
    ('信息Display后，图表起始位置under移', 'After info display, chart start position moves down'),
    ('绘制统一 2x2 四面板图表。', 'Draw unified 2x2 quad-panel chart.'),
    ('每Test Type静态分析图统一is 4 子图：', 'Each test type static analysis is unified as 4 sub-charts:'),
    ('左on: TTFT / Latency指标', 'Top-left: TTFT / Latency metrics'),
    ('右on: 速度/Throughput指标', 'Top-right: Speed / Throughput metrics'),
    ('左under: Input Throughput / 缓存指标', 'Bottom-left: Input Throughput / Cache metrics'),
    ('右under: Output Throughput / TPOT 指标', 'Bottom-right: Output Throughput / TPOT metrics'),
    ('X 轴Data', 'X-axis data'),
    ('4 子图Configure列表，每 dict 包含:', '4 sub-chart config list, each dict contains:'),
    ('Y 轴Data (list[float])', 'Y-axis data (list[float])'),
    ('子图标题 (str)', 'Sub-chart title (str)'),
    ('Y 轴Label (str)', 'Y-axis label (str)'),
    ('折线颜色 (str)', 'Line color (str)'),
    ('若is None 则跳过该面板', 'If None, skip this panel'),
    ('总标题', 'Main title'),
    ('X 轴Label', 'X-axis label'),
    ('系统信息', 'System info'),
    ('Calculate 2x2 子图位置', 'Calculate 2x2 sub-chart positions'),
    ('水平间距', 'Horizontal gap'),
    ('垂直间距', 'Vertical gap'),
    ('子图位置:', 'Sub-chart positions:'),
    ('左on', 'Top-left'),
    ('右on', 'Top-right'),
    ('左under', 'Bottom-left'),
    ('右under', 'Bottom-right'),
    ('will图表Save到字节流', 'Save chart to byte stream'),
    ('图片格式', 'Image format'),
    ('will图表Saveis Base64 编码字符串', 'Save chart as Base64 encoded string'),
    ('Base64 编码字符串', 'Base64 encoded string'),
    ('will图表Save到文件', 'Save chart to file'),
    ('从 DataFrame Create chart快捷函数', 'Quick function to create chart from DataFrame'),
    ('包含Data DataFrame', 'DataFrame containing data'),
    ('X 轴列名', 'X-axis column name'),
    ('Y 轴列名', 'Y-axis column name'),
    ('Chart Title', 'Chart Title'),
    ('CreateConcurrencyTest静态图表', 'Create concurrency test static chart'),
    ('包含 concurrency and指标列 DataFrame', 'DataFrame with concurrency and metric columns'),
    ('要绘制指标列名', 'Metric column name to plot'),
    ('按ConcurrencySort', 'Sort by concurrency'),
    ('based on指标确定 Y 轴Label', 'Determine Y-axis label based on metric'),
    ('系统Output Throughput (tokens/s)', 'System Output Throughput (tokens/s)'),
    ('Create预PadTest静态图表', 'Create prefill test static chart'),
    ('包含 prefill_tokens and指标列 DataFrame', 'DataFrame with prefill_tokens and metric columns'),
    ('预Pad速度 (tokens/s)', 'Prefill Speed (tokens/s)'),
    ('预Pad速度 vs 输入长度', 'Prefill Speed vs Input Length'),
    ('按输入长度Sort', 'Sort by input length'),
    ('输入长度 (tokens)', 'Input Length (tokens)'),
    ('HTML 报告Generate', 'HTML Report Generation'),
    ('Generate静态 HTML 报告（可直接in浏览器in打开）', 'Generate static HTML report (can be opened directly in browser)'),
    ('Test Results列表', 'Test results list'),
    ('HTML 字符串', 'HTML string'),
    ('lang=\"zh-CN\"', 'lang=\"en\"'),
    ('LLM 性能Test Report', 'LLM Performance Test Report'),
    ('性能Test Report', 'Performance Test Report'),
    ('under载图片', 'Download Image'),
]

# =====================================================================
# FILE: ui/advanced_panels.py
# =====================================================================
ADVANCED = [
    ('高级Test Panels Module', 'Advanced Test Panels Module'),
    ('包含质量Test、A/B 对比、高级Evaluationetc.功能', 'Contains quality testing, A/B comparison, advanced evaluation features'),
    ('启动优化：', 'Startup Optimization:'),
    ('评估模块useLatencyImport，减少启动时间', 'Evaluation modules use lazy import to reduce startup time'),
    ('LatencyImport模块（按需Load）', 'Lazy Import Modules (loaded on demand)'),
    ('LatencyLoadQuality Assessment模块', 'Lazy load quality assessment module'),
    ('LatencyLoad增强Evaluation模块', 'Lazy load enhanced evaluation module'),
    ('CheckQuality Assessment模块is否可用', 'Check if quality assessment module is available'),
    ('Check增强Evaluation模块is否可用', 'Check if enhanced evaluation module is available'),
    ('兼容性变量（Latency检测）', 'Compatibility variables (lazy detection)'),
    ('willin首次访问时检测', 'Will be detected on first access'),
    ('Latency检测Quality Assessment可用性', 'Lazy detect quality assessment availability'),
    ('Latency检测增强Evaluation可用性', 'Lazy detect enhanced evaluation availability'),
    ('Render质量Test面板', 'Render quality test panel'),
    ('侧边栏Configure字典', 'Sidebar configuration dictionary'),
    ('is否TriggerTest', 'Whether test was triggered'),
    ('Model质量Test', 'Model Quality Test'),
    ('use公开Test set (MMLU, GSM8K etc.) 评估Model推理能力and知识水平。', 'Use public benchmarks (MMLU, GSM8K, etc.) to evaluate model reasoning and knowledge.'),
    ('Latency检测andLoad模块', 'Lazy detect and load module'),
    ('Quality Assessment模块Load failed，Please check evaluators 目录is否完整。', 'Quality assessment module failed to load. Please check if the evaluators directory is complete.'),
    ('Initialize质量TestStatus', 'Initialize quality test status'),
    ('质量Test Parameters', 'Quality Test Parameters'),
    ('Data集选择', 'Dataset selection'),
    ('选择test data集', 'Select test datasets'),
    ('基础Dataset', 'Basic Datasets'),
    ('通用知识 (57学科)', 'General knowledge (57 subjects)'),
    ('小学数学推理', 'Elementary math reasoning'),
    ('高etc.数学竞赛', 'Advanced math competitions'),
    ('Python 代码Generate', 'Python code generation'),
    ('in文知识评估', 'Chinese knowledge evaluation'),
    ('高级Dataset', 'Advanced Datasets'),
    ('高级推理Test set', 'Advanced reasoning test sets'),
    ('研究生级别科学推理', 'Graduate-level scientific reasoning'),
    ('科学常识推理', 'Scientific commonsense reasoning'),
    ('真实性Test', 'Truthfulness testing'),
    ('评估参数', 'Evaluation Parameters'),
    ('Model类型', 'Model Type'),
    ('标准Model (Standard)', 'Standard Model'),
    ('思考Model (Reasoning/CoT)', 'Reasoning Model (CoT)'),
    ('代码Model (Code)', 'Code Model'),
    ('思考', 'Reasoning'),
    ('代码', 'Code'),
    ('Sample模式', 'Sampling Mode'),
    ('快速抽样 (100题/Dataset)', 'Quick sampling (100 questions/dataset)'),
    ('inetc.抽样 (500题)', 'Medium sampling (500 questions)'),
    ('Custom抽样', 'Custom sampling'),
    ('完整Test (全部)', 'Full test (all)'),
    ('Data集Sample count映射表', 'Dataset sample count mapping'),
    ('已选Dataset最小Sample count:', 'Min sample count for selected datasets:'),
    ('Question数量', 'Number of questions'),
    ('Few-shot 示例数', 'Few-shot examples'),
    ('详细Parameter Settings', 'Detailed Parameter Settings'),
    ('Concurrency请求数', 'Concurrent requests'),
    ('Suggestion: 本地Model 1-2, API Model 4-10', 'Recommended: Local model 1-2, API model 4-10'),
    ('开始按钮', 'Start button'),
    ('开始Quality Assessment', 'Start Quality Assessment'),
    ('请in左侧选择at least onetest data集。', 'Please select at least one test dataset in the left panel.'),
    ('DisplayResult', 'Display results'),
    ('运行质量Test', 'Run quality test'),
    ('GetLatencyLoad模块', 'Get lazy-loaded module'),
    ('Quality Assessment模块not可用', 'Quality assessment module not available'),
    ('Display进度UI', 'Display progress UI'),
    ('Test进行in...', 'Test in progress...'),
    ('currentlyInitializeQuality Assessment... Dataset:', 'Initializing quality assessment... Datasets:'),
    ('BuildConfigure', 'Build configuration'),
    ('RegisterEvaluator类', 'Register evaluator classes'),
    ('进度Callback', 'Progress callback'),
    ('运行评估', 'Run evaluation'),
    ('Create新事件循环（修复 Python 3.10+ 非主Thread问题）', 'Create new event loop (fix Python 3.10+ non-main thread issue)'),
    ('Cleanup事件循环引用', 'Cleanup event loop reference'),
    ('Quality Assessment完成! 共评估', 'Quality assessment complete! Evaluated'),
    ('Dataset,', 'datasets,'),
    ('正确', 'correct'),
    ('Quality Assessment出错:', 'Quality assessment error:'),
    ('Render A/B Model Comparison面板', 'Render A/B model comparison panel'),
    ('in相同Test seton对比两 models性能，并进行Statistics显著性分析。', 'Compare two models on the same test set with statistical significance analysis.'),
    ('A/B 对比模块Load failed。', 'A/B comparison module failed to load.'),
    ('Model A (侧边栏Configure)', 'Model A (sidebar config)'),
    ('Model B (对比对象)', 'Model B (comparison target)'),
    ('每集Sample count', 'Samples per dataset'),
    ('Few-shot 数量', 'Number of few-shots'),
    ('开始对比评估', 'Start Comparison'),
    ('运行 A/B 对比Test', 'Run A/B comparison test'),
    ('增强Evaluation模块not可用', 'Enhanced evaluation module not available'),
    ('ConfigModel A', 'Configure Model A'),
    ('ConfigModel B', 'Configure Model B'),
    ('对比评估完成！', 'Comparison complete!'),
    ('对比评估失败:', 'Comparison failed:'),
    ('Display A/B Comparison Results', 'Display A/B comparison results'),
    ('对比报告', 'Comparison Report'),
    ('汇总表格', 'Summary table'),
    ('总体表现', 'Overall Performance'),
    ('差异 (B-A)', 'Difference (B-A)'),
    ('显著', 'Significant'),
    ('not显著', 'Not significant'),
    ('Statistics显著性', 'Statistical Significance'),
    ('Render高级Evaluation分析面板', 'Render advanced evaluation analysis panel'),
    ('高级Evaluation分析', 'Advanced Evaluation Analysis'),
    ('提供进阶Evaluation工具：一致性Test、鲁棒性Test、智能AnswerParse演示etc.。', 'Provides advanced evaluation tools: consistency testing, robustness testing, smart answer parser demo.'),
    ('增强Evaluation模块Load failed，Please check core/ 目录is否包含必要模块。', 'Enhanced evaluation module failed to load. Please check if core/ directory contains required modules.'),
    ('智能Parse演示', 'Smart Parser Demo'),
    ('一致性Test', 'Consistency Test'),
    ('鲁棒性Test', 'Robustness Test'),
    ('智能AnswerParse器演示', 'Smart Answer Parser Demo'),
    ('智能AnswerParse器use分层策略提取Answer：', 'Smart answer parser uses a layered strategy to extract answers:'),
    ('规则匹配', 'Pattern matching'),
    ('(快速)', '(fast)'),
    ('匹配 `\\\\boxed{}`, `####` etc.标准格式', 'Matches standard formats like `\\\\boxed{}`, `####`'),
    ('启发式规则', 'Heuristic rules'),
    ('模式匹配如 \"answer is X\"', 'Pattern matching like "answer is X"'),
    ('LLM 兜底', 'LLM fallback'),
    ('(optional)', '(optional)'),
    ('当置信度低时use LLM 提取', 'Uses LLM extraction when confidence is low'),
    ('输入Model响应', 'Enter model response'),
    ('Answer类型', 'Answer Type'),
    ('Correct answer（optional）', 'Correct answer (optional)'),
    ('ParseAnswer', 'Parse Answer'),
    ('提取Answer', 'Extracted Answer'),
    ('置信度', 'Confidence'),
    ('Parse方法', 'Parse Method'),
    ('Answer正确！', 'Answer correct!'),
    ('AnswerError。预期:', 'Answer incorrect. Expected:'),
    ('Parse failed:', 'Parse failed:'),
    ('一致性Test对同一问题进行多次Query，评估Model answer稳定性。', 'Consistency testing queries the same question multiple times to evaluate model answer stability.'),
    ('每问题Test次数', 'Tests per question'),
    ('稳定性阈值', 'Stability threshold'),
    ('Test问题', 'Test question'),
    ('Correct answer', 'Correct answer'),
    ('will对问题运行', 'Will run question'),
    ('次，一致率 ≥', 'times, consistency rate ≥'),
    ('视is稳定', 'considered stable'),
    ('开始一致性Test', 'Start Consistency Test'),
    ('一致性TestneedConfigure API Connection。请先in左侧Configure API。', 'Consistency testing requires API connection. Please configure API in the left panel first.'),
    ('鲁棒性Test评估Model对输入微扰敏感性。', 'Robustness testing evaluates model sensitivity to input perturbations.'),
    ('扰动演示', 'Perturbation Demo'),
    ('输入原始问题', 'Enter original question'),
    ('扰动类型', 'Perturbation Type'),
    ('Apply扰动', 'Apply Perturbation'),
    ('原始问题:', 'Original question:'),
    ('扰动后问题:', 'Perturbed question:'),
    ('扰动详情:', 'Perturbation details:'),
    ('CreateEvaluator', 'Create evaluator'),
]

# =====================================================================
# FILE: ui/batch_test.py
# =====================================================================
BATCH = [
    ('Batch Test UI 组件', 'Batch Test UI Components'),
    ('提供Batch Test用户界面：', 'Provides batch test user interface:'),
    ('批量Test Configuration编辑器', 'Batch test configuration editor'),
    ('Batch Test执行界面', 'Batch test execution interface'),
    ('批量Test Results展示', 'Batch test results display'),
    ('Batch TestHistory', 'Batch test history'),
    ('Render批量Test Configuration编辑器', 'Render batch test configuration editor'),
    ('ConfigureBatch Test', 'Configure Batch Test'),
    ('基本信息', 'Basic Information'),
    ('Batch Test名称', 'Batch Test Name'),
    ('多Model性能对比Test', 'Multi-model performance comparison test'),
    ('描述（optional）', 'Description (optional)'),
    ('描述此Batch Test目...', 'Describe the purpose of this batch test...'),
    ('执行Options', 'Execution Options'),
    ('并行执行', 'Parallel Execution'),
    ('同时运行多 tests（实验性功能）', 'Run multiple tests simultaneously (experimental)'),
    ('最大并行数', 'Max Parallel'),
    ('遇错停止', 'Stop on Error'),
    ('某Test failed时停止Batch Test', 'Stop batch test when a test fails'),
    ('Test itemsConfigure', 'Test Item Configuration'),
    ('InitializeTest items列表', 'Initialize test items list'),
    ('AddTest items按钮', 'Add test item button'),
    ('AddTest items', 'Add Test Item'),
    ('Displayand编辑Test items', 'Display and edit test items'),
    ('Test items', 'Test Item'),
    ('编辑Test items', 'Edit test item'),
    ('Test名称', 'Test Name'),
    ('启用', 'Enabled'),
    ('Save修改', 'Save Changes'),
    ('Delete此Test items', 'Delete this test item'),
    ('快速Add功能', 'Quick Add Feature'),
    ('快速Add', 'Quick Add'),
    ('从预设Add', 'Add from Presets'),
    ('这里can列出Saved预设供快速Add', 'List saved presets for quick add here'),
    ('批量Import', 'Batch Import'),
    ('on传Configure文件 (JSON)', 'Upload configuration file (JSON)'),
    ('on传批量Test Configuration文件', 'Upload batch test configuration file'),
    ('ImportConfigure', 'Import Configuration'),
    ('ImportTest items', 'Import test items'),
    ('已Import', 'Imported'),
    (' tests items', ' test items'),
    ('Import失败:', 'Import failed:'),
    ('Save Config按钮', 'Save config button'),
    ('Save批量Test Configuration', 'Save Batch Test Configuration'),
    ('Please enterBatch Test名称', 'Please enter a batch test name'),
    ('请至少Add一 tests items', 'Please add at least one test item'),
    ('CreateConfigure', 'Create configuration'),
    ('批量Test Configuration', 'Batch test configuration'),
    ('Saved', 'saved'),
    ('清空', 'Clear All'),
    ('Batch Test执行界面', 'Batch Test Execution Interface'),
    ('RenderBatch Test执行界面', 'Render batch test execution interface'),
    ('执行Batch Test', 'Execute Batch Test'),
    ('选择SavedConfigure', 'Select saved configuration'),
    ('暂noSave批量Test Configuration，请先inon方CreateConfigure', 'No saved batch test configurations yet. Please create one above.'),
    ('选择批量Test Configuration', 'Select Batch Test Configuration'),
    ('DisplayConfigure信息', 'Display configuration info'),
    ('no法Load Config:', 'Cannot load configuration:'),
    ('Configure详情', 'Configuration Details'),
    ('描述:', 'Description:'),
    ('no', 'None'),
    ('Test items数量:', 'Number of test items:'),
    ('并行执行:', 'Parallel execution:'),
    ('is', 'Yes'),
    ('否', 'No'),
    ('最大并行数:', 'Max parallel:'),
    ('Test items列表:', 'Test items list:'),
    ('执行按钮', 'Execute button'),
    ('开始Batch Test', 'Start Batch Test'),
    ('Stop Test', 'Stop Test'),
    ('Display进度', 'Display progress'),
    ('RenderBatch Test进度', 'Render batch test progress'),
    ('Test进度', 'Test Progress'),
    ('进度条', 'Progress bar'),
    ('失败', 'Failed'),
    ('跳过', 'Skipped'),
    ('当前执行Test', 'Currently executing test'),
    ('currently执行:', 'Currently executing:'),
    ('Real-time logging', 'Real-time logs'),
    ('执行Log', 'Execution Log'),
    ('Display最近10条', 'Show last 10 entries'),
    ('批量Test Results展示', 'Batch Test Results Display'),
    ('Render批量Test Results', 'Render batch test results'),
    ('批量Test Results', 'Batch Test Results'),
    ('Get所hasResult', 'Get all results'),
    ('暂no批量Test Results', 'No batch test results yet'),
    ('选择Result查看', 'Select results to view'),
    ('选择Test Results', 'Select Test Results'),
    ('Parse result', 'Parse result'),
    ('no法LoadResult:', 'Cannot load result:'),
    ('DisplayResult摘要', 'Display result summary'),
    ('总Test items', 'Total Items'),
    ('完成', 'Completed'),
    ('Display对比表格', 'Display comparison table'),
    ('Test对比', 'Test Comparison'),
    ('under载对比 CSV', 'Download Comparison CSV'),
    ('no可用Data', 'No data available'),
    ('DisplayDetailed Results', 'Display detailed results'),
    ('查看Detailed Results', 'View Detailed Results'),
    ('未知', 'Unknown'),
    ('Load批量Test Results', 'Load batch test results'),
    ('use最新Result文件', 'Use latest result file'),
    ('重新构造 BatchTestResult 对象', 'Reconstruct BatchTestResult object'),
    ('LoadResult失败:', 'Failed to load result:'),
    ('Batch Test主界面', 'Batch Test Main Interface'),
    ('RenderBatch Test主界面', 'Render batch test main interface'),
    ('Label页', 'Tabs'),
    ('执行', 'Execute'),
    ('历史', 'History'),
    ('Render批量Test History', 'Render batch test history'),
    ('批量Test History', 'Batch Test History'),
    ('暂no批量Test History', 'No batch test history'),
    ('DisplayHistory', 'Display history'),
    ('总Test:', 'Total Tests:'),
    ('完成:', 'Completed:'),
    ('失败:', 'Failed:'),
    ('耗时:', 'Duration:'),
    ('从 session_state Get批量Test Configuration', 'Get batch test configuration from session_state'),
    ('未命名Batch Test', 'Unnamed Batch Test'),
    ('清除Batch Testwill话Data', 'Clear batch test session data'),
]


# =====================================================================
# Process all files
# =====================================================================

file_translations = {
    'ui/charts.py': CHARTS,
    'ui/onboarding.py': ONBOARDING,
    'ui/test_control_panel.py': CONTROL_PANEL,
    'ui/static_chart_generator.py': STATIC_CHART,
    'ui/advanced_panels.py': ADVANCED,
    'ui/batch_test.py': BATCH,
}

print("Phase 4: Deep file-specific translation")
print("=" * 60)

total_remaining = 0
for filepath, reps in file_translations.items():
    if os.path.exists(filepath):
        remaining = translate_file(filepath, reps)
        if remaining >= 0:
            total_remaining += remaining
            print(f"  {remaining:4d} remaining | {filepath}")
        else:
            print(f"  no change  | {filepath}")
    else:
        print(f"  not found  | {filepath}")

print(f"\nTotal remaining Chinese segments: {total_remaining}")
