"""
Comprehensive Chinese-to-English translation script for the LLM Benchmark Platform.
Handles all major UI, config, and core files.
"""
import os
import re


def translate_file(filepath, replacements):
    """Apply replacements to a file."""
    try:
        with open(filepath, encoding='utf-8') as f:
            content = f.read()
    except (OSError, UnicodeError):
        return 0

    original = content
    for old, new in replacements:
        content = content.replace(old, new)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        # Count remaining Chinese
        remaining = len(re.findall(r'[\u4e00-\u9fff]+', content))
        return remaining
    return -1  # No changes made

# ========================
# UNIVERSAL replacements (apply to ALL files)
# ========================
UNIVERSAL = [
    # Test type names (used across many files)
    ('并发性能测试', 'Concurrency Test'),
    ('Prefill 压力测试', 'Prefill Stress Test'),
    ('长上下文测试', 'Long Context Test'),
    ('分段上下文测试', 'Segmented Context Test'),
    ('并发-上下文 综合测试', 'Concurrency-Context Matrix Test'),
    ('并发-上下文综合测试', 'Concurrency-Context Matrix Test'),
    ('自定义文本测试', 'Custom Text Test'),
    ('全部测试', 'All Tests'),
    ('稳定性测试', 'Stability Test'),

    # Common UI labels
    ('开始并发测试', 'Start Concurrency Test'),
    ('开始并发性能测试', 'Start Concurrency Test'),
    ('开始 Prefill 测试', 'Start Prefill Test'),
    ('开始长上下文测试', 'Start Long Context Test'),
    ('开始分段测试', 'Start Segmented Test'),
    ('开始综合测试', 'Start Matrix Test'),
    ('开始自定义测试', 'Start Custom Test'),
    ('开始全部测试', 'Start All Tests'),
    ('开始稳定性测试', 'Start Stability Test'),
    ('开始测试', 'Start Test'),

    # Common status/state
    ('正在启动', 'Starting'),
    ('测试中...', 'Testing...'),
    ('运行中', 'Running'),
    ('已暂停', 'Paused'),
    ('已取消', 'Cancelled'),
    ('已完成', 'Completed'),
    ('空闲', 'Idle'),
    ('暂停测试', 'Pause Test'),
    ('停止测试', 'Stop Test'),
    ('恢复测试', 'Resume Test'),
    ('正在暂停', 'Pausing'),
    ('正在停止', 'Stopping'),

    # Common parameter labels
    ('选择并发级别', 'Select Concurrency Levels'),
    ('自定义并发数 (逗号分隔)', 'Custom Concurrency (comma-separated)'),
    ('自定义并发数', 'Custom Concurrency'),
    ('每级请求轮数', 'Rounds Per Level'),
    ('每级轮数', 'Rounds Per Level'),
    ('输入 Token 长度', 'Input Token Length'),
    ('最大要生成的Token数', 'Max Output Tokens'),
    ('最大生成Token数', 'Max Output Tokens'),
    ('最大生成 Token 数', 'Max Output Tokens'),
    ('最大输出 Token', 'Max Output Tokens'),
    ('上下文长度', 'Context Length'),
    ('并发数', 'Concurrency'),
    ('并发', 'Concurrency'),

    # Common headers and sections
    ('参数设置', 'Parameter Settings'),
    ('测试参数', 'Test Parameters'),
    ('测试配置', 'Test Configuration'),
    ('测试结果', 'Test Results'),
    ('测试报告', 'Test Report'),
    ('性能洞察', 'Performance Insights'),
    ('详细结果', 'Detailed Results'),
    ('图表分析', 'Chart Analysis'),
    ('最佳性能统计', 'Best Performance Stats'),

    # Common buttons and actions
    ('下载结果', 'Download Results'),
    ('下载报告', 'Download Report'),
    ('下载静态分析图', 'Download Static Chart'),
    ('下载完整 HTML 报告', 'Download Full HTML Report'),
    ('查看完整原始数据', 'View Full Raw Data'),
    ('保存配置', 'Save Config'),
    ('加载配置', 'Load Config'),
    ('删除配置', 'Delete Config'),

    # Common info/warnings
    ('请确认', 'Please confirm'),
    ('请检查', 'Please check'),
    ('请选择', 'Please select'),
    ('请输入', 'Please enter'),
    ('数据为空', 'Data is empty'),
    ('没有数据', 'No data'),
    ('缺少必要', 'Missing required'),
    ('加载失败', 'Load failed'),
    ('保存失败', 'Save failed'),
    ('测试失败', 'Test failed'),
    ('报告失败', 'Report failed'),
    ('数据中缺少', 'Missing in data'),
    ('没有有效的', 'No valid'),

    # Common metrics/technical terms
    ('系统吞吐量', 'System Throughput'),
    ('输出吞吐量', 'Output Throughput'),
    ('输入吞吐量', 'Input Throughput'),
    ('总吞吐量', 'Total Throughput'),
    ('首字延迟', 'Time To First Token'),
    ('缓存命中', 'Cache Hit'),
    ('缓存命中率', 'Cache Hit Rate'),
    ('成功率', 'Success Rate'),
    ('请求成功率', 'Request Success Rate'),
    ('吞吐量', 'Throughput'),
    ('延迟', 'Latency'),

    # Common formatting/display
    ('总请求数', 'Total Requests'),
    ('总输入 Tokens', 'Total Input Tokens'),
    ('总输出 Tokens', 'Total Output Tokens'),
    ('成功', 'succeeded'),
    ('平均', 'Average'),
    ('峰值', 'Peak'),
    ('最佳', 'Best'),
    ('最差', 'Worst'),
    ('最高', 'Highest'),
    ('最低', 'Lowest'),

    # Streamlit status
    ('测试完成', 'Test completed'),
    ('测试开始', 'Test started'),
    ('测试取消', 'Test cancelled'),
    ('测试错误', 'Test error'),

    # Comments - common patterns
    ('# 延迟导入', '# Lazy import'),
    ('# 创建图表', '# Create chart'),
    ('# 添加', '# Add'),
    ('# 设置', '# Set'),
    ('# 获取', '# Get'),
    ('# 计算', '# Calculate'),
    ('# 检查', '# Check'),
    ('# 更新', '# Update'),
    ('# 处理', '# Process'),
    ('# 生成', '# Generate'),
    ('# 保存', '# Save'),
    ('# 加载', '# Load'),
    ('# 删除', '# Delete'),
    ('# 初始化', '# Initialize'),
    ('# 验证', '# Validate'),
    ('# 构建', '# Build'),
    ('# 渲染', '# Render'),
    ('# 显示', '# Display'),
    ('# 格式化', '# Format'),
    ('# 返回', '# Return'),
    ('# 配置', '# Config'),
    ('# 测试', '# Test'),
    ('# 结果', '# Result'),
    ('# 错误', '# Error'),
    ('# 日志', '# Log'),
    ('# 状态', '# Status'),
    ('# 模型', '# Model'),
    ('# 数据', '# Data'),
    ('# 导出', '# Export'),
    ('# 导入', '# Import'),
    ('# 清理', '# Cleanup'),
]

# ========================
# FILE-SPECIFIC replacements
# ========================

# test_panels.py specific
TEST_PANELS = [
    ('"""测试面板模块', '"""Test Panels Module'),
    ('提供各种测试类型的配置面板，包括：', 'Provides configuration panels for various test types:'),
    ('启动优化：', 'Startup optimization:'),
    ('BenchmarkRunner 使用延迟导入，减少启动时间', 'BenchmarkRunner uses lazy import to reduce startup time'),
    ('Bug修复：', 'Bug fixes:'),
    ('为所有输入控件添加唯一 key，避免参数变化时触发意外测试', 'Added unique keys to all input controls to prevent accidental test triggers on parameter changes'),
    ('延迟获取 BenchmarkRunner 类', 'Lazy-load BenchmarkRunner class'),
    ('渲染所有测试面板', 'Render all test panels'),
    ('当前选择的测试类型', 'Currently selected test type'),
    ('测试执行函数', 'Test execution function'),
    ('如果测试被触发返回 True，否则 False', 'Returns True if test was triggered, False otherwise'),
    ('严格校准输入 Prompt 的 Token 长度（自动根据长度匹配指令后缀）', 'Strictly calibrate input prompt token length (auto-match instruction suffix based on length)'),
    ('正在启动并发测试...', 'Starting concurrency test...'),
    ('正在启动 Prefill 测试...', 'Starting Prefill test...'),
    ('正在启动长上下文测试...', 'Starting long context test...'),
    ('正在启动分段测试...', 'Starting segmented test...'),
    ('正在启动综合测试...', 'Starting matrix test...'),
    ('正在启动自定义测试...', 'Starting custom test...'),
    ('正在启动全部测试...', 'Starting all tests...'),
    ('正在启动稳定性测试...', 'Starting stability test...'),
    ('选择上下文长度级别', 'Select Context Length Levels'),
    ('自定义上下文长度 (逗号分隔)', 'Custom Context Lengths (comma-separated)'),
    ('选择 Prefill 长度级别', 'Select Prefill Length Levels'),
    ('自定义 Prefill 长度 (逗号分隔)', 'Custom Prefill Lengths (comma-separated)'),
    ('每级请求数', 'Requests Per Level'),
    ('分段数量', 'Number of Segments'),
    ('分段步长', 'Segment Step Size'),
    ('起始长度', 'Start Length'),
    ('总上下文长度', 'Total Context Length'),
    ('测试文本', 'Test Text'),
    ('输入自定义测试文本', 'Enter custom test text'),
    ('持续时间(分钟)', 'Duration (minutes)'),
    ('采样间隔(秒)', 'Sampling Interval (seconds)'),
    ('选择要运行的测试', 'Select Tests to Run'),
    ('已选择', 'Selected'),
    ('个测试', ' tests'),
    ('目标', 'Target'),
    ('起始上下文长度', 'Start Context Length'),
    ('上下文长度步长 (K)', 'Context Length Step (K)'),
    ('上下文长度级别数', 'Number of Context Levels'),
    ('含所有图表', 'All Charts'),
    ('图表请参见 Web 界面', 'See charts in Web UI'),
    ('每个Concurrency级别的 Prefill Token数', 'Prefill Tokens per Concurrency Level'),
    ('每个级别的 Prefill Token 数', 'Prefill Tokens per Level'),
    ('测试执行器', 'Test executor'),
]

# test_control_panel.py specific
TEST_CONTROL = [
    ('"""统一测试控制面板模块', '"""Unified Test Control Panel Module'),
    ('提供集中化的测试控制界面：', 'Provides centralized test control interface:'),
    ('统一的测试启动按钮', 'Unified test start button'),
    ('测试进度显示', 'Test progress display'),
    ('测试状态监控', 'Test status monitoring'),
    ('测试控制操作（启动/停止/恢复）', 'Test control operations (start/stop/resume)'),
    ('测试状态定义', 'Test status definitions'),
    ('等待执行', 'Waiting'),
    ('执行中', 'Executing'),
    ('暂停中', 'Paused'),
    ('已完成', 'Completed'),
    ('已失败', 'Failed'),
    ('已跳过', 'Skipped'),
    ('测试进度', 'Test Progress'),
    ('当前状态', 'Current Status'),
    ('已执行', 'Executed'),
    ('剩余', 'Remaining'),
    ('预计剩余时间', 'Estimated Remaining Time'),
    ('已用时间', 'Elapsed Time'),
    ('总进度', 'Overall Progress'),
]

# test_runner.py specific
TEST_RUNNER = [
    ('"""测试执行模块', '"""Test Execution Module'),
    ('提供测试执行流程封装，包括：', 'Provides test execution workflow, including:'),
    ('测试状态管理', 'Test state management'),
    ('进度显示', 'Progress display'),
    ('实时日志', 'Real-time logging'),
    ('系统信息捕获', 'System info capture'),
    ('测试结果存储', 'Test result storage'),
    ('测试执行器类', 'Test executor class'),
    ('初始化测试执行器', 'Initialize test executor'),
    ('测试完成！共耗时', 'Test completed! Total time'),
    ('测试被取消', 'Test was cancelled'),
    ('测试执行出错', 'Test execution error'),
    ('正在执行', 'Executing'),
    ('执行测试', 'Execute test'),
    ('采集系统信息', 'Collecting system info'),
    ('保存测试结果', 'Saving test results'),
]

# onboarding.py specific
ONBOARDING = [
    ('"""新手引导系统模块', '"""Onboarding System Module'),
    ('提供首次使用时的帮助和引导：', 'Provides first-time use help and guidance:'),
    ('功能介绍', 'Feature Introduction'),
    ('分步教程', 'Step-by-step Tutorial'),
    ('快速开始指南', 'Quick Start Guide'),
    ('常见问题解答', 'FAQ'),
    ('引导状态管理', 'Onboarding State Management'),
    ('新手引导状态类', 'Onboarding state class'),
    ('引导步骤定义', 'Onboarding step definitions'),
    ('欢迎使用', 'Welcome to'),
    ('LLM 性能基准测试平台', 'LLM Performance Benchmark Platform'),
    ('下一步', 'Next'),
    ('上一步', 'Previous'),
    ('开始使用', 'Get Started'),
    ('跳过引导', 'Skip Onboarding'),
    ('帮助与引导', 'Help & Guide'),
    ('[OK] 已完成引导', '[OK] Onboarding completed'),
    (' 重新引导', ' Restart Onboarding'),
    ('使用帮助', 'Help'),
    ('步骤', 'Step'),
    ('配置 API', 'Configure API'),
    ('选择测试', 'Select Test'),
    ('开始基准测试', 'Start Benchmark'),
    ('查看结果', 'View Results'),
    ('第一步', 'Step 1'),
    ('第二步', 'Step 2'),
    ('第三步', 'Step 3'),
    ('第四步', 'Step 4'),
    ('在左侧边栏', 'In the left sidebar'),
    ('填写 API Key', 'Enter API Key'),
    ('选择模型', 'Select model'),
    ('选择供应商', 'Select provider'),
    ('配置参数', 'Configure parameters'),
    ('点击开始', 'Click start'),
    ('等待测试完成', 'Wait for test to complete'),
    ('分析结果', 'Analyze results'),
    ('导出报告', 'Export report'),
    ('常见问题', 'FAQ'),
    ('如何添加自定义API供应商？', 'How to add a custom API provider?'),
    ('在侧边栏最下方', 'At the bottom of the sidebar'),
    ('如何选择合适的Tokenizer？', 'How to choose the right Tokenizer?'),
    ('推荐使用', 'Recommended'),
    ('如何解读测试结果？', 'How to interpret test results?'),
    ('测试完成后系统会自动生成', 'After testing, the system will automatically generate'),
    ('带有图表和分析', 'with charts and analysis'),
    ('帮助/引导', 'Help/Guide'),
]

# charts.py specific
CHARTS = [
    ('根据最大值返回合适的格式字符串。', 'Returns the appropriate format string based on max value.'),
    ('整数', 'integer'),
    ('位小数', 'decimal places'),
    ('其他', 'other'),
    ('格式化单个数值', 'Format a single value'),
    ('简化标题', 'Simplified title'),
    ('默认颜色', 'Default color'),
    ('创建图表', 'Create chart'),
    ('添加相对性能视图（如果启用且y为数值列）', 'Add relative performance view (if enabled and y is numeric)'),
    ('使用相对性能作为文本显示', 'Use relative performance as text display'),
    ('更新y轴标签，添加相对性能标注', 'Update y-axis label, add relative performance annotation'),
    ('最大=100%', 'max=100%'),
    ('相对性能', 'Relative Perf'),
    ('改进的坐标轴标准化', 'Improved axis normalization'),
    ('动态设置y轴范围，确保有足够的边距', 'Dynamically set y-axis range with sufficient margin'),
    ('改进的对数坐标判断逻辑', 'Improved log scale detection logic'),
    ('过滤掉', 'Filter out'),
    ('的值，避免', 'values to avoid'),
    ('值导致比值计算错误', 'values causing ratio calculation errors'),
    ('计算比值', 'Calculate ratio'),
    ('只有当比值确实极大', 'Only when ratio is extremely large'),
    ('时才启用对数坐标', 'enable log scale'),
    ('对数坐标', 'Log Scale'),
    ('改进布局和样式', 'Improved layout and styles'),
    ('左对齐标题', 'Left-align title'),
    ('明确区分置信区间和误差棒的颜色', 'Distinguish confidence interval and error bar colors'),
    ('置信区间用红色表示', 'Confidence interval in red'),
    ('确定目标颜色', 'Determine target color'),
    ('颜色序列逻辑', 'Color sequence logic'),
    ('如果指定了分组列', 'If group column specified'),
    ('和基准颜色', 'and base color'),
    ('则生成基于该基准颜色的渐变色系', 'generate gradient based on base color'),
    ('单线条单色', 'Single line single color'),
    ('添加相对性能线', 'Add relative performance line'),
    ('设置双y轴', 'Set dual y-axis'),
    ('更新主y轴标签', 'Update main y-axis label'),
    ('相对最佳性能', 'Relative to Best'),
    ('明确区分置信区间和误差棒', 'Distinguish confidence interval and error bars'),
    ('通用样式 update', 'Common style update'),
    ('智能格式化', 'Smart formatting'),
    ('加粗数值', 'Bold values'),
    ('数值字体变大', 'Larger value font'),
    ('针对单线条（自定义颜色）的特殊模仿样式', 'Special style for single line (custom color)'),
    ('模拟静态图的', 'Simulate static chart'),
    ('空心/靶心', 'hollow/bullseye'),
    ('效果：白色填充 + 粗颜色边框', 'effect: white fill + thick color border'),
    ('线条更粗', 'Thicker line'),
    ('多线条时，保留自动颜色（或我们的渐变色），但增大标记', 'Multi-line: keep auto-color (or gradient), enlarge markers'),
    ('标题和布局增强', 'Title and layout enhancement'),
    ('标题更大更黑', 'Larger and darker title'),
    ('居中', 'Center'),
    ('强制 X 轴为分类型，使点等间距分布', 'Force X-axis to categorical for equal spacing'),
    ('简化标题，移除硬件/模型信息子标题，保持界面整洁', 'Simplified title, removed hardware/model info subtitle, keep interface clean'),
    ('专门用于显示相对性能的柱状图', 'Bar chart specifically for relative performance'),
    ('添加绝对值柱状图（浅色）', 'Add absolute value bars (light color)'),
    ('绝对值', 'Absolute'),
    ('添加相对性能柱状图（深色）', 'Add relative performance bars (dark color)'),
    ('Plotly 柱状图失败', 'Plotly bar chart failed'),
    ('Plotly 折线图失败', 'Plotly line chart failed'),
    ('箱线图生成失败', 'Box plot generation failed'),
    ('小提琴图生成失败', 'Violin plot generation failed'),
    ('散点图生成失败', 'Scatter plot generation failed'),
    ('性能汇总图表失败', 'Performance summary chart failed'),
    ('相对性能图表失败', 'Relative performance chart failed'),
    ('如果全为0，则不触发', 'If all zeros, do not trigger'),
]

# Now apply replacements to files
files_to_translate = {
    'ui/test_panels.py': TEST_PANELS + UNIVERSAL,
    'ui/test_control_panel.py': TEST_CONTROL + UNIVERSAL,
    'ui/test_runner.py': TEST_RUNNER + UNIVERSAL,
    'ui/onboarding.py': ONBOARDING + UNIVERSAL,
    'ui/charts.py': CHARTS + UNIVERSAL,
    'ui/log_viewer.py': UNIVERSAL,
    'ui/markdown_summary.py': UNIVERSAL,
    'ui/quality_reports.py': UNIVERSAL,
    'ui/export.py': UNIVERSAL,
    'ui/batch_test.py': UNIVERSAL,
    'ui/advanced_panels.py': UNIVERSAL,
    'ui/history_browser.py': UNIVERSAL,
    'ui/evaluation_dashboard.py': UNIVERSAL,
    'ui/realtime_dashboard.py': UNIVERSAL,
    'ui/dashboard_components.py': UNIVERSAL,
    'ui/dataset_manager.py': UNIVERSAL,
    'ui/comparison_page.py': UNIVERSAL,
    'ui/thinking_components.py': UNIVERSAL,
    'ui/static_chart_generator.py': UNIVERSAL,
    'ui/styled_tables.py': UNIVERSAL,
    'config/settings.py': UNIVERSAL,
    'config/test_config_loader.py': UNIVERSAL,
    'core/benchmark_runner.py': UNIVERSAL,
    'core/error_messages.py': UNIVERSAL,
    'core/metrics.py': UNIVERSAL,
    'core/test_runner.py': TEST_RUNNER + UNIVERSAL,
    'core/test_config.py': UNIVERSAL,
    'core/task_config.py': UNIVERSAL,
    'core/system_info.py': UNIVERSAL,
    'core/standard_report.py': UNIVERSAL,
    'core/smart_answer_parser.py': UNIVERSAL,
    'core/prompt_template.py': UNIVERSAL,
    'core/response_parser.py': UNIVERSAL,
    'core/enhanced_parser.py': UNIVERSAL,
    'core/enhanced_evaluator.py': UNIVERSAL,
    'core/evaluation_report.py': UNIVERSAL,
    'core/failure_analyzer.py': UNIVERSAL,
    'core/model_comparator.py': UNIVERSAL,
    'core/batch_test.py': UNIVERSAL,
    'core/llm_judge.py': UNIVERSAL,
    'core/quality_evaluator.py': UNIVERSAL,
    'core/reasoning_evaluator.py': UNIVERSAL,
    'core/result_comparator.py': UNIVERSAL,
    'core/consistency_tester.py': UNIVERSAL,
    'core/robustness_tester.py': UNIVERSAL,
    'core/thinking_params.py': UNIVERSAL,
    'core/request_logger.py': UNIVERSAL,
    'core/response_cache.py': UNIVERSAL,
    'core/retry_handler.py': UNIVERSAL,
    'core/dataset_manager.py': UNIVERSAL,
    'core/tokenizer_utils.py': UNIVERSAL,
    'core/providers/openai.py': UNIVERSAL,
    'core/providers/gemini.py': UNIVERSAL,
    'core/providers/factory.py': UNIVERSAL,
    'core/certification_report.py': UNIVERSAL,
    'core/dataset_loader.py': UNIVERSAL,
    'core/history_manager.py': UNIVERSAL,
    'core/database/manager.py': UNIVERSAL,
    'core/database/connection.py': UNIVERSAL,
    'core/database/schema.py': UNIVERSAL,
    'core/database/backup.py': UNIVERSAL,
    'core/database/migrations.py': UNIVERSAL,
    'core/database/__init__.py': UNIVERSAL,
    'core/models/test_run.py': UNIVERSAL,
    'core/models/test_result.py': UNIVERSAL,
    'core/models/report.py': UNIVERSAL,
    'core/models/api_log.py': UNIVERSAL,
    'core/models/exec_log.py': UNIVERSAL,
    'core/models/__init__.py': UNIVERSAL,
    'core/repositories/base.py': UNIVERSAL,
    'core/repositories/test_run.py': UNIVERSAL,
    'core/repositories/test_result.py': UNIVERSAL,
    'core/repositories/report.py': UNIVERSAL,
    'core/repositories/api_log.py': UNIVERSAL,
    'core/repositories/exec_log.py': UNIVERSAL,
    'core/repositories/__init__.py': UNIVERSAL,
    'core/services/data_export.py': UNIVERSAL,
    'core/services/data_import.py': UNIVERSAL,
    'core/services/__init__.py': UNIVERSAL,
    'utils/helpers.py': UNIVERSAL,
    'utils/logger.py': UNIVERSAL,
    'utils/custom_config.py': UNIVERSAL,
    'utils/test_config_manager.py': UNIVERSAL,
    'utils/log_server.py': UNIVERSAL,
    'utils/dataset_downloader.py': UNIVERSAL,
    'utils/download_new_datasets.py': UNIVERSAL,
    'utils/download_aime2025.py': UNIVERSAL,
    'utils/download_arena_hard.py': UNIVERSAL,
    'utils/download_global_piqa.py': UNIVERSAL,
    'utils/download_longbench.py': UNIVERSAL,
}

print("Starting translation...")
translated = 0
remaining_total = 0

for filepath, reps in files_to_translate.items():
    if os.path.exists(filepath):
        remaining = translate_file(filepath, reps)
        if remaining >= 0:
            translated += 1
            remaining_total += remaining
            status = f"({remaining} Chinese segments remaining)" if remaining > 0 else "(clean)"
            print(f"  Translated: {filepath} {status}")
        else:
            print(f"  No changes: {filepath}")
    else:
        print(f"  Not found:  {filepath}")

print(f"\nTranslated {translated} files. {remaining_total} Chinese segments still remaining across all files.")
