#!/usr/bin/env python3
"""
Phase 5: Final sweep – translate all remaining Chinese in UI files.

Covers: comparison_page, test_runner, dashboard_components, dataset_manager,
        thinking_components, log_viewer, export, history_browser,
        markdown_summary, evaluation_dashboard, quality_reports
"""

import os
import re

# ── Global phrase table (longest first to avoid partial collisions) ──────────

TRANSLATIONS = {
    # === comparison_page.py ===
    "History对比 (Historical Comparison)": "Historical Comparison",
    "暂No History。请先运行一些基准Test。": "No history yet. Please run some benchmark tests first.",
    "选择要对比记录": "Select Records to Compare",
    "选择记录 (支持多选)": "Select Records (multi-select)",
    "Please select至少两记录进行对比。": "Please select at least two records to compare.",
    "no法Load选in记录。": "Unable to load selected records.",
    "选in记录in没has包含has效test data。": "Selected records do not contain valid test data.",
    "对比图表": "Comparison Charts",
    "综合性能对比 (Radar Chart)": "Overall Performance Comparison (Radar Chart)",
    "多Model综合性能对比": "Multi-Model Performance Comparison",
    "单 items指标详情": "Individual Metric Details",
    "选择Comparison Metrics": "Select Comparison Metric",
    "指标 '{metric}' in选inDatainnot存in。": "Metric '{metric}' does not exist in selected data.",
    "查看详细Data (Detailed Data)": "View Detailed Data",
    # === test_runner.py ===
    "Configure字典，包含 api_base_url, model_id, api_key etc.": "Configuration dict containing api_base_url, model_id, api_key, etc.",
    "Execute test并管理Status": "Execute test and manage status",
    "Test函数": "Test function",
    "Test运行器类": "Test runner class",
    "Test Type名称": "Test type name",
    "传递给Test函数参数": "Parameters passed to test function",
    "Test ResultsData框": "Test results DataFrame",
    "Checkis否isRestore模式": "Check if in resume mode",
    "从进度Resume Test: ": "Resuming test from saved progress: ",
    "RestoreCompletedResult": "Restore completed results",
    "Log窗口已Initialize... etc.待Test started": "Log window initialized... waiting for test to start",
    "输出预览区域已就绪，etc.待首 requests完成...": "Output preview area ready, waiting for first request to complete...",
    "# 捕获系统信息": "# Capture system info",
    "捕获系统信息": "Capture system information",
    "# CalculateTotal Requests": "# Calculate total requests",
    "CalculateTotal Requests": "Calculate total requests",
    "# 捕获Test Configuration": "# Capture test configuration",
    "捕获Test Configuration": "Capture test configuration",
    "Test completed! 耗时: ": "Test completed! Duration: ",
    "s。ResultSaved到 ": "s. Results saved to ",
    "Test已由用户停止。": "Test stopped by user.",
    "Test运行时发生Error: ": "Error occurred during test execution: ",
    "# 对Result DataFrame 进行列重Sort，确保 UI andunder载一致性": "# Reorder Result DataFrame columns for UI and download consistency",
    "# 清除Restore标志": "# Clear resume flags",
    "# based onTest ResultsSetStatus": "# Set status based on test results",
    "Test正常完成": "Test completed normally",
    "Merge用户Custom系统信息": "Merge user custom system info",
    "# 回退值": "# Fallback values",
    "engine_name notSet回退值 — provider notis引擎": "engine_name has no fallback — provider is not the engine",
    "# 引擎指推理后端（如 vLLM、SGLang、TRT-LLM etc.），用户可in侧边栏手动填写": "# Engine refers to inference backend (e.g. vLLM, SGLang, TRT-LLM), users can fill in manually via sidebar",
    "AsyncExecute test": "Execute test asynchronously",
    "# Create新事件循环（修复 Python 3.10+ 非主Thread问题）": "# Create new event loop (fix for Python 3.10+ non-main thread issues)",
    "Cleanup事件循环引用": "Clean up event loop reference",
    "# Backward compatibility函数接口": "# Backward compatibility function interface",
    "CreateTest执行器实例": "Create test executor instance",
    "# Initialize运行器": "# Initialize runner",
    "# CreateFilename": "# Create filename",
    "# Create UI 组件": "# Create UI components",
    # === dashboard_components.py ===
    "实时Test指标": "Real-time Test Metrics",
    "活跃请求": "Active Requests",
    "当前currentlyProcess请求数": "Number of requests currently being processed",
    "succeeded完成请求总数": "Total successfully completed requests",
    "失败": "Failed",
    "失败请求总数": "Total failed requests",
    "请求Success Rate百分比": "Request success rate percentage",
    "Average首Token时间": "Average time to first token",
    "Average每secondsGenerateToken数": "Average tokens generated per second",
    "etc.待test data...": "Waiting for test data...",
    "活跃": "Active",
    "完成": "Completed",
    "失败": "Failed",
    "请求StatusGrid": "Request Status Grid",
    "暂no请求": "No requests yet",
    # === dataset_manager.py ===
    "Dataset管理 (Dataset Management)": "Dataset Management",
    "on传新Dataset": "Upload New Dataset",
    "选择 CSV or JSON 文件": "Select a CSV or JSON file",
    "SaveDataset": "Save Dataset",
    "currentlyValidate并Save...": "Validating and saving...",
    "Savesucceeded！": "Saved successfully!",
    "Datasetmust包含 'prompt' column.optional列: 'expected_output', 'id'。": "Dataset must contain a 'prompt' column. Optional columns: 'expected_output', 'id'.",
    "SavedDataset": "Saved Datasets",
    "暂noDataset。请on传一新Dataset。": "No datasets yet. Please upload a new dataset.",
    "预览": "Preview",
    "已Delete ": "Deleted ",
    "Delete失败": "Delete failed",
    "预览: ": "Preview: ",
    "Display前 ": "Showing first ",
    " 行": " rows",
    "no法Load预览": "Unable to load preview",
    # === thinking_components.py ===
    "Phase 6: UI 增强组件 (Enhanced UI Components)": "Phase 6: Enhanced UI Components",
    "提供推理Model专用 UI 组件：": "Provides specialized UI components for reasoning models:",
    "推理内容折叠展示": "Collapsible reasoning content display",
    "思考指标Visualization": "Thinking metrics visualization",
    "报告Export按钮": "Report export buttons",
    "实时流式预览": "Real-time streaming preview",
    "# 尝试Import核心模块": "# Try importing core modules",
    "# ifImport失败，提供占位": "# If import fails, provide placeholder",
    "Render可折叠推理内容展示": "Render collapsible reasoning content display",
    "推理内容": "Reasoning content",
    "正文内容": "Main body content",
    "折叠区域标题": "Collapsible section title",
    "is否defaultExpand": "Whether to expand by default",
    "最大高度 (px)": "Maximum height (px)",
    " 字符)": " chars)",
    "最终输出:": "Final Output:",
    "Render思考指标卡片": "Render thinking metrics cards",
    "指标字典or ThinkingMetricsResult": "Metrics dict or ThinkingMetricsResult",
    "每行卡片数": "Cards per row",
    "# Convertis字典": "# Convert to dict",
    "# 定义要Display指标": "# Define metrics to display",
    "推理Token": "Reasoning Tokens",
    "推理占比": "Reasoning Ratio",
    "总Token": "Total Tokens",
    "预估成本": "Est. Cost",
    "# Create列": "# Create columns",
    "RenderLatency仪表盘": "Render latency gauge dashboard",
    "首Token时间 (ms)": "Time to first token (ms)",
    "首正文时间 (ms)": "Time to first useful token (ms)",
    "总耗时 (ms)": "Total time (ms)",
    "最大值 (ms)": "Maximum value (ms)",
    "# TTFT 仪表盘": "# TTFT gauge",
    "# TTUT 仪表盘": "# TTUT gauge",
    "# 总耗时仪表盘": "# Total time gauge",
    "Render Token 分布Pie Chart": "Render token distribution pie chart",
    "推理 Token": "Reasoning Tokens",
    "正文 Token": "Content Tokens",
    "输入 Token": "Input Tokens",
    "输入": "Input",
    "推理": "Reasoning",
    "正文": "Content",
    "暂no Token Data": "No token data yet",
    "Token\u003cbr\u003e分布": "Token<br>Distribution",
    "Render平台信息卡片": "Render platform info card",
    "平台标识": "Platform identifier",
    "未知平台: ": "Unknown platform: ",
    "参数位置:": "Param Location:",
    "推理字段:": "Reasoning Field:",
    "支持预算:": "Budget Support:",
    "支持强度:": "Effort Support:",
    "Render报告Export按钮": "Render report export buttons",
    "报告Build器实例": "Report builder instance",
    "Filename前缀": "Filename prefix",
    "点击under载 JSON": "Click to download JSON",
    "# 临时文件": "# Temporary file",
    "点击under载 Markdown": "Click to download Markdown",
    "点击under载 HTML": "Click to download HTML",
    "Render实时流式预览": "Render real-time streaming preview",
    "当前累积正文内容": "Current accumulated body content",
    "当前累积推理内容": "Current accumulated reasoning content",
    "is否currently流式接收": "Whether currently streaming",
    "is否Display推理内容": "Whether to show reasoning content",
    "# Status指示器": "# Status indicator",
    "接收in...": "Receiving...",
    "完成": "Complete",
    "# 推理预览": "# Reasoning preview",
    "# 正文预览": "# Content preview",
    "输出内容:": "Output Content:",
    "Render质量Score卡片": "Render quality score card",
    "综合分": "Overall score",
    "准确性": "Accuracy",
    "连贯性": "Coherence",
    "完整性": "Completeness",
    "综合Score / 10": "Overall Score / 10",
    # === log_viewer.py ===
    "Render增强Log查看器": "Render enhanced log viewer",
    "BenchmarkLogger实例": "BenchmarkLogger instance",
    "Streamlit占位符（用于实时Update）": "Streamlit placeholder (for real-time updates)",
    "最大Display条数": "Maximum entries to display",
    "is否启用Filter控件": "Whether to enable filter controls",
    "紧凑模式（用于Real-time logging）": "Compact mode (for real-time logging)",
    "# 紧凑模式：仅Display最近Log文本": "# Compact mode: show only recent log text",
    "# 完整模式：Statistics、Filter、多视图": "# Full mode: statistics, filters, multiple views",
    "Render紧凑Log视图（用于实时Update）": "Render compact log view (for real-time updates)",
    "# Display彩色文本Log": "# Display colored text log",
    "Render完整Log查看器": "Render full log viewer",
    "# Statistics信息卡片": "# Statistics info cards",
    "总Log": "Total Logs",
    "# Filter控件": "# Filter controls",
    "选择要DisplayLog Level": "Select log levels to display",
    "搜索": "Search",
    "输入关键词搜索...": "Enter keywords to search...",
    "inLog消息in搜索": "Search within log messages",
    "Display指标": "Show Metrics",
    "inLoginDisplayPerformance Metrics": "Show performance metrics in logs",
    "# ApplyFilter": "# Apply filters",
    "# DisplayLog": "# Display logs",
    "没has匹配Log": "No matching logs",
    "# Options卡视图": "# Tab views",
    "文本视图": "Text View",
    "表格视图": "Table View",
    "Statistical analysis": "Statistical Analysis",
    "# 文本视图 - 带颜色and格式": "# Text view - with colors and formatting",
    "# 表格视图": "# Table view",
    "Render彩色文本Log": "Render colored text log",
    "# 紧凑模式：简单列表": "# Compact mode: simple list",
    "# 完整模式：带边框and背景": "# Full mode: with borders and background",
    "willLogConvertisDataFrame": "Convert logs to DataFrame",
    "时间": "Time",
    "级别": "Level",
    "消息": "Message",
    "RenderLog分析": "Render log analytics",
    "Log Level分布": "Log Level Distribution",
    "数量": "Count",
    "暂noLogData": "No log data yet",
    "# 时间线分析": "# Timeline analysis",
    "Log Time线": "Log Timeline",
    "# 按minutesStatisticsLog数量": "# Count logs per minute",
    "Log活动时间线": "Log Activity Timeline",
    "# ErrorandWarning详情": "# Error and warning details",
    "问题详情": "Issue Details",
    "最近5条": "last 5",
    "Performance Metrics摘要": "Performance Metrics Summary",
    "Performance Metrics摘要": "Performance Metrics Summary",
    "范围: ": "Range: ",
    "CreateLogDownload button": "Create log download buttons",
    "ExportLog": "Export Logs",
    "# JSONExport": "# JSON export",
    "under载 JSON": "Download JSON",
    "结构化JSON格式，包含所has字段": "Structured JSON format with all fields",
    "# 文本Export": "# Text export",
    "under载 TXT": "Download TXT",
    "可读文本格式": "Readable text format",
    "# CSVExport": "# CSV export",
    "under载 CSV": "Download CSV",
    "CSV格式，可用Excel打开": "CSV format, can be opened with Excel",
    # === export.py ===
    "under载 Excel 报告": "Download Excel Report",
    "under载 HTML 报告": "Download HTML Report",
    "图表 ": "Chart ",
    "Data表 ": "Data Table ",
    "Generate时间: ": "Generated: ",
    "静态Chart Export功能 (借鉴 llm-performance-test.html 风格)": "Static Chart Export (inspired by llm-performance-test.html style)",
    "Export静态性能图表 (PNG格式)": "Export static performance chart (PNG format)",
    "use美观Line Chart风格，带hasData点Labeland阴影效果。": "Uses elegant line chart style with data point labels and shadow effects.",
    "包含Data DataFrame": "DataFrame containing the data",
    "X 轴列名": "X-axis column name",
    "Y 轴列名": "Y-axis column name",
    "Chart Title": "Chart title",
    "X 轴Label": "X-axis label",
    "Y 轴Label": "Y-axis label",
    "折线颜色 (default青绿色)": "Line color (default teal)",
    "输出Filename": "Output filename",
    "BytesIO 对象包含 PNG 图片Data": "BytesIO object containing PNG image data",
    "静态图表Export failed: ": "Static chart export failed: ",
    "Export预Padand输出速度双图表报告 (类似 llm-performance-test.html 风格)": "Export prefill and output speed dual-chart report (similar to llm-performance-test.html style)",
    "Test Results列表，每 items包含:": "Test results list, each item contains:",
    "输入长度": "Input length",
    "预Pad速度 (token/s)": "Prefill speed (token/s)",
    "输出速度 (token/s)": "Output speed (token/s)",
    "系统信息字典，包含:": "System info dict, containing:",
    "Process器": "Processor",
    "主板": "Mainboard",
    "内存": "Memory",
    "显卡": "GPU",
    "操作系统": "Operating System",
    "推理引擎名称": "Inference engine name",
    "Model name": "Model name",
    "Test时间 (optional，default当前时间)": "Test time (optional, defaults to current time)",
    "性能报告图表Export failed: ": "Performance report chart export failed: ",
    "under载静态图表": "Download Static Chart",
    "Create静态图表under载链接": "Create static chart download link",
    "图表字节流": "Chart byte stream",
    "under载Filename": "Download filename",
    "链接按钮文字": "Link button text",
    "HTML under载链接": "HTML download link",
    "Return DataFrame in一存in列名, 全not存in则Return None": "Return the first existing column name in DataFrame, or None if none exist",
    "安全提取列Data, 转is float list": "Safely extract column data, convert to float list",
    "based onTest TypeExport统一格式 2×2 四面板汇总图表 (PNG)。": "Export unified 2×2 quad-panel summary chart (PNG) based on test type.",
    "统一布局:": "Unified layout:",
    "左on: TTFT(Latency)": "Top-left: TTFT (Latency)",
    "右on: 速度指标": "Top-right: Speed Metrics",
    "左under: Input Throughput": "Bottom-left: Input Throughput",
    "右under: Output Throughput": "Bottom-right: Output Throughput",
    "汇总Data DataFrame": "Summary DataFrame",
    "提供商": "Provider",
    "optional系统信息": "Optional system info",
    "失败则Return None": "Returns None on failure",
    "# ---- 公共标题逻辑 ----": "# ---- Common title logic ----",
    "性能Test": "Performance Test",
    "# ---- matrix Test → 多Line Chart（保留特殊Process，becausehasConcurrency维度）----": "# ---- matrix test → multi-line chart (special handling, has concurrency dimension) ----",
    "系统Output Throughput (tokens/s)": "System Output Throughput (tokens/s)",
    "# ---- otherTest Type → 统一 2×2 四面板 ----": "# ---- Other test types → unified 2×2 quad panel ----",
    "# 公共列名Parse": "# Common column name resolution",
    "# 确定 X 轴": "# Determine X-axis",
    "输入长度 (tokens)": "Input Length (tokens)",
    "# Build 4 面板Configure": "# Build 4-panel config",
    "# 左on: TTFT": "# Top-left: TTFT",
    "# 输入/Prefill 相关": "# Input/Prefill related",
    "# 右on: Prefill Speed / 主要速度指标": "# Top-right: Prefill Speed / primary speed metric",
    "Prefill 速度": "Prefill Speed",
    "# 左under: Input Throughput or Cache Hit率（分段Test特殊Process）": "# Bottom-left: Input Throughput or Cache Hit Rate (special handling for segmented test)",
    "Cache Hit率": "Cache Hit Rate",
    "# 缓存": "# Cache",
    "系统Input Throughput": "System Input Throughput",
    "# 右under: Output Throughput or TPOT": "# Bottom-right: Output Throughput or TPOT",
    "系统Output Throughput": "System Output Throughput",
    "# 输出/Decode 相关": "# Output/Decode related",
    "Average每TokenGenerate时间 (TPOT)": "Average Time Per Output Token (TPOT)",
    "# Checkis否至少has 1 has效面板": "# Check if at least 1 valid panel exists",
    "汇总图表Export failed: ": "Summary chart export failed: ",
    # === history_browser.py ===
    "History浏览 UI": "History Browser UI",
    "提供TestHistory浏览、搜索、Export功能。": "Provides test history browsing, search, and export functionality.",
    "RenderHistory浏览器": "Render history browser",
    "TestHistory": "Test History",
    "# 搜索and筛选": "# Search and filter",
    "搜索": "Search",
    "输入ModelID、Labelor备注...": "Enter model ID, label, or notes...",
    "全部": "All",
    "时间范围": "Time Range",
    "今天": "Today",
    "最近7天": "Last 7 Days",
    "最近30天": "Last 30 Days",
    "最近90天": "Last 90 Days",
    "# BuildQuery": "# Build query",
    "# DisplayStatistics": "# Display statistics",
    "# Display列表": "# Display list",
    "暂noTest记录": "No test records yet",
    "# 分页": "# Pagination",
    "页码": "Page",
    "# Display记录": "# Display records",
    "# 分页信息": "# Pagination info",
    "条，共 ": " of ",
    " 条记录": " records",
    "QueryTest运行": "Query test runs",
    "# 基础Query": "# Base query",
    "# 类型筛选": "# Type filter",
    "# 时间筛选": "# Time filter",
    "DisplayStatistics信息": "Display statistics info",
    "总Test数": "Total Tests",
    "Model数": "Models",
    "Render单 tests运行卡片": "Render single test run card",
    "# Status颜色": "# Status colors",
    "# 操作按钮": "# Action buttons",
    "详情": "Details",
    "指标": "Metrics",
    "已Delete": "Deleted",
    "DisplayTest运行Detailed Metrics": "Display detailed test run metrics",
    "# GetResultStatistics": "# Get result statistics",
    "最小 TTFT": "Min TTFT",
    "最大 TPS": "Max TPS",
    "最小 TPS": "Min TPS",
    "ExportTest运行": "Export test run",
    "已Export: ": "Exported: ",
    "RenderData import面板": "Render data import panel",
    "Import历史Data": "Import Historical Data",
    "will现has CSV Test ResultsImport到Databasein": "Import existing CSV test results into the database",
    "# 选择Import源": "# Select import source",
    "Import源": "Import Source",
    "单文件": "Single File",
    "整目录": "Entire Directory",
    "CSV File path": "CSV file path",
    "For example: raw_data/model_id/benchmark_results.csv": "e.g.: raw_data/model_id/benchmark_results.csv",
    "Model ID（optional，留空自动推断）": "Model ID (optional, leave blank for auto-detection)",
    "Test Type（optional）": "Test Type (optional)",
    "开始Import": "Start Import",
    "Importin...": "Importing...",
    "succeededImport ": "Successfully imported ",
    " 条记录": " records",
    "目录路径": "Directory Path",
    "For example: raw_data/": "e.g.: raw_data/",
    "扫描并Import": "Scan and Import",
    "扫描in...": "Scanning...",
    "完成！succeededImport ": "Complete! Successfully imported ",
    " 文件，共 ": " files, total ",
    "查看Error (": "View Errors (",
    " 条)": " items)",
    "Render仪表盘": "Render dashboard",
    "仪表盘": "Dashboard",
    "# 总览": "# Overview",
    "Database大小": "Database Size",
    "Backup数": "Backups",
    "# 按ModelStatistics": "# Statistics by model",
    "#### 按ModelStatistics": "#### Statistics by Model",
    "# 按类型Statistics": "# Statistics by type",
    "#### 按Test TypeStatistics": "#### Statistics by Test Type",
    "# 最近Test": "# Recent tests",
    "#### 最近Test": "#### Recent Tests",
    # === markdown_summary.py ===
    "### Test摘要 (Summary)\\n\\n": "### Test Summary\\n\\n",
    "总Data量": "Total Data Volume",
    "输入 ": "Input ",
    " tokens, 输出 ": " tokens, Output ",
    "Concurrency扩展性": "Concurrency Scalability",
    "Concurrency从 ": "When concurrency increased from ",
    " 增加到 ": " to ",
    " 时，TTFT 从 ": ", TTFT went from ",
    "增加到": "increased to",
    "变化is": "changed to",
    "Peak性能": "Peak Performance",
    "inConcurrency ": "at concurrency ",
    " 时达到HighestSystem Throughput ": " reached peak system throughput of ",
    "Peak单流 TPS": "Peak Single-Stream TPS",
    "TTFT 趋势": "TTFT Trend",
    "出现最大跳增": "showed largest spike",
    "随Concurrency增加平稳on升。": "increased steadily with concurrency.",
    "Throughput饱and点": "Throughput Saturation",
    " 后Throughput增速低于 5%。": " throughput growth fell below 5%.",
    "未达到饱and，仍has增长空间。": "not yet saturated, still has growth capacity.",
    "Prefill 速度趋势": "Prefill Speed Trend",
    "输入长度从 ": "When input length increased from ",
    "Prefill 速度从 ": "prefill speed went from ",
    " t/s 变is ": " t/s to ",
    " t/s (保持率 ": " t/s (retention rate ",
    "速度衰减拐点": "Speed Degradation Inflection",
    "出现最大骤降": "showed largest drop",
    "速度衰减模式": "Speed Degradation Pattern",
    "随输入增加平稳衰减。": "decreased steadily with increasing input length.",
    "TTFT 增长模式": "TTFT Growth Pattern",
    "超线性增长 (TTFT 增长 ": "Super-linear growth (TTFT grew ",
    "x 而输入仅增 ": "x while input only grew ",
    "近似线性。": "approximately linear.",
    "亚线性 (TTFT 增长慢于输入增长)": "Sub-linear (TTFT grew slower than input)",
    "长文性能衰减": "Long-Text Performance Degradation",
    "onunder文从 ": "when context grew from ",
    " 变is ": " to ",
    "Generate稳定性": "Generation Stability",
    "单流 TPS 从 ": "single-stream TPS went from ",
    "TTFT 拐点": "TTFT Inflection Point",
    "随onunder文增加均匀增长。": "grew uniformly with increasing context.",
    "TPS 全程波动": "Overall TPS Fluctuation",
    "波动较大。": "showing significant fluctuation.",
    "TPS 全程稳定性": "Overall TPS Stability",
    "表现稳定。": "showing stable performance.",
    "命in ": "hit ",
    "缓存增长": "Cache Growth",
    "首段缓存率 ": "first-segment cache rate ",
    "% → 末段缓存率 ": "% → last-segment cache rate ",
    "Peak缓存率": "Peak Cache Rate",
    "缓存率趋势": "Cache Rate Trend",
    "持续增长，缓存效果随分段积累显著。": "continuously increasing, cache effectiveness grows significantly with segments.",
    "存in波动，缓存效果not稳定。": "shows fluctuation, cache effectiveness is unstable.",
    "整体稳定。": "overall stable.",
    "BestConfigure": "Best Configuration",
    " 时达到HighestThroughput ": " reached peak throughput of ",
    "WorstConfigure": "Worst Configuration",
    " 时Throughputis ": " throughput was ",
    "TTFT 范围": "TTFT Range",
    "Concurrency ": "Concurrency ",
    " × onunder文 ": " × context ",
    # === evaluation_dashboard.py ===
    "Streamlit 组件，用于VisualizationEvaluationResult。": "Streamlit component for visualizing evaluation results.",
    "EvaluationResultDashboard": "Evaluation Results Dashboard",
    "Render完整EvaluationResultDashboard": "Render full evaluation results dashboard",
    "EvaluationResult字典，包含 models, summary etc.字段": "Evaluation results dict containing models, summary, etc.",
    "Dashboard标题": "Dashboard title",
    "# 元信息": "# Meta info",
    "Test名称": "Test Name",
    "Test时间": "Test Time",
    "# Model对比表格": "# Model comparison table",
    "# 图表区域": "# Chart area",
    "RenderModel Comparison表格": "Render model comparison table",
    "Model性能对比": "Model Performance Comparison",
    "平台": "Platform",
    "正确数": "Correct",
    "AverageLatency": "Avg Latency",
    "推理质量": "Reasoning Quality",
    "# 高亮Best值": "# Highlight best values",
    "RenderAccuracy对比图": "Render accuracy comparison chart",
    "Accuracy对比": "Accuracy Comparison",
    "# 颜色方案": "# Color scheme",
    "RenderLatency对比图": "Render latency comparison chart",
    "Latency对比": "Latency Comparison",
    "AverageLatency (ms)": "Average Latency (ms)",
    "Render失败分析面板": "Render failure analysis panel",
    "失败分析": "Failure Analysis",
    "# 失败率": "# Failure rate",
    "失败率": "Failure Rate",
    "失败Sample count": "Failed Samples",
    "# 类别分布Pie Chart": "# Category distribution pie chart",
    "# 改进Suggestion": "# Improvement suggestions",
    "改进Suggestion:": "Improvement Suggestions:",
    "Render一致性Test面板": "Render consistency test panel",
    "一致性Test": "Consistency Test",
    "整体一致率": "Overall Consistency",
    "整体Accuracy": "Overall Accuracy",
    "稳定样本比例": "Stable Sample Ratio",
    "Render鲁棒性Test面板": "Render robustness test panel",
    "鲁棒性Test": "Robustness Test",
    "原始Accuracy": "Original Accuracy",
    "Accuracyunder降": "Accuracy Drop",
    "整体鲁棒性": "Overall Robustness",
    "# 按扰动类型敏感性": "# Sensitivity by perturbation type",
    "扰动敏感性分析:": "Perturbation Sensitivity Analysis:",
    "敏感度 (%)": "Sensitivity (%)",
    "Render推理质量分解": "Render reasoning quality breakdown",
    "推理质量分析": "Reasoning Quality Analysis",
    "暂no推理质量Data": "No reasoning quality data yet",
    "# 提取各维度Average分": "# Extract average scores per dimension",
    "连贯性": "Coherence",
    "完整性": "Completeness",
    "相关性": "Relevance",
    "正确性": "Correctness",
    "效率": "Efficiency",
    "# 闭合": "# Close the loop",
    "Render样本详情表格": "Render sample details table",
    "样本详情": "Sample Details",
    "# FilterOptions": "# Filter options",
    "筛选": "Filter",
    "仅正确": "Correct Only",
    "仅Error": "Errors Only",
    "Sort": "Sort",
    "default": "Default",
    "按Latency": "By Latency",
    "按推理质量": "By Reasoning Quality",
    "# 筛选": "# Filter",
    "# Sort": "# Sort",
    "# Display": "# Display",
    "样本 ": "Sample ",
    "问题:": "Question:",
    "预测Answer:": "Predicted Answer:",
    "RenderExport区域": "Render export section",
    "Export Report": "Export Report",
    "under载 JSON": "Download JSON",
    "under载 CSV": "Download CSV",
    "[查看完整报告]()": "[View Full Report]()",
    "Render迷你Dashboard（用于侧边栏or小空间）": "Render mini dashboard (for sidebar or small space)",
    "# Accuracy进度条": "# Accuracy progress bar",
    "**AverageLatency**": "**Average Latency**",
    "**推理质量**": "**Reasoning Quality**",
    "输入: ": "Input: ",
    "推理: ": "Reasoning: ",
    "输出: ": "Output: ",
    # === quality_reports.py ===
    "质量Test Report模块 - GenerateQuality AssessmentVisualization报告": "Quality test report module - generates quality assessment visualization reports",
    "GenerateQuality Assessment汇总表": "Generate quality assessment summary table",
    "Evaluation result字典 {dataset_name: EvaluationResult}": "Evaluation results dict {dataset_name: EvaluationResult}",
    "汇总 DataFrame": "Summary DataFrame",
    "# Calculate AI 裁判修正数": "# Calculate AI judge correction count",
    "正确数": "Correct",
    "总样本": "Total Samples",
    "裁判修正": "Judge Corrections",
    "耗时(seconds)": "Duration (s)",
    "# AddPerformance Metrics (ifhas)": "# Add performance metrics (if available)",
    "输入Tokens": "Input Tokens",
    "输出Tokens": "Output Tokens",
    "评估时间": "Eval Time",
    "RenderAccuracyBar Chart": "Render accuracy bar chart",
    "各DatasetAccuracy": "Accuracy by Dataset",
    "Render能力Radar Chart (适用于多Dataset评估)": "Render capability radar chart (for multi-dataset evaluation)",
    "# 闭合Radar Chart": "# Close the radar chart",
    "Model能力": "Model Capability",
    "Model能力Radar Chart": "Model Capability Radar",
    "Render分类别AccuracyHeatmap": "Render per-category accuracy heatmap",
    "# 提取Data": "# Extract data",
    "# 按AccuracySort": "# Sort by accuracy",
    "# 限制Display数量": "# Limit display count",
    " 分类别Accuracy (Top ": " Per-Category Accuracy (Top ",
    "类别": "Category",
    "Render增强版Error分析面板": "Render enhanced error analysis panel",
    "not再直接Return DataFrame，而isin这里负责Renderandunder载": "No longer returns DataFrame directly, handles rendering and download here",
    "# 提取Error样本": "# Extract error samples",
    "太棒！in该Dataseton没has发现Error样本。": "Great! No error samples found in this dataset.",
    "# --- 新增: Display自动失败分析报告 ---": "# --- New: Display automated failure analysis report ---",
    "智能失败分析报告": "Automated Failure Analysis Report",
    "总体失败率": "Overall Failure Rate",
    "##### 主要失败原因": "##### Top Failure Causes",
    "##### 改进Suggestion": "##### Improvement Suggestions",
    "# 分布图": "# Distribution chart",
    "失败原因分布": "Failure Cause Distribution",
    "# 1. 控制栏：筛选与Export": "# 1. Control bar: filter and export",
    "# 提取类别用于筛选": "# Extract categories for filtering",
    "筛选Error类别 (共 ": "Filter Error Category (total ",
    " Error)": " errors)",
    "# FilterData": "# Filter data",
    "# Build完整 CSV Data用于under载": "# Build complete CSV data for download",
    "Export所hasError，not仅仅isFilter后": "Export all errors, not just filtered ones",
    "under载Error报告": "Download Error Report",
    "under载包含 Prompt and完整响应所hasError样本": "Download all error samples with prompts and full responses",
    "# 2. Error列表概览 (Display部分)": "# 2. Error list overview (display section)",
    "#### Error列表": "#### Error List",
    "类别": "Category",
    "问题摘要": "Question Summary",
    "Correct answer": "Correct Answer",
    "Model预测": "Model Prediction",
    "*列表仅Display前 ": "*Showing only the first ",
    " 条，请useon方按钮under载完整报告，oruseunder方工具查看详情。*": " items. Use the button above to download the full report or the tool below for details.*",
    "# 3. 深度诊断工具": "# 3. Deep diagnosis tool",
    "#### 深度诊断": "#### Deep Diagnosis",
    "选择一 samples ID 以查看完整 Prompt andModel原始响应，分析Error原因。": "Select a sample ID to view the full prompt and model raw response for error analysis.",
    "选择样本 ID": "Select Sample ID",
    "# 查找选inError details": "# Find selected error details",
    "Model完整响应": "Model Full Response",
    "提取预测": "Extracted Prediction",
    "RenderPerformance Metrics面板": "Render performance metrics panel",
    "# 收集has性能DataResult": "# Collect results with performance data",
    "输入 Tokens": "Input Tokens",
    "输出 Tokens": "Output Tokens",
    "暂noPerformance MetricsData": "No performance metrics data yet",
    "# 性能汇总表": "# Performance summary table",
    "# 图表展示": "# Chart display",
    "in Streamlit inRender完整Quality Assessment报告": "Render full quality assessment report within Streamlit",
    "is否Display详细信息": "Whether to show detailed information",
    "暂noEvaluation result": "No evaluation results yet",
    "# 标题": "# Title",
    "ModelQuality Assessment报告": "Model Quality Assessment Report",
    "# 汇总表格": "# Summary table",
    "### 评估汇总": "### Evaluation Summary",
    "# FormatAccuracy列": "# Format accuracy column",
    "# AccuracyBar Chart": "# Accuracy bar chart",
    "need至少 3 Dataset才能DisplayRadar Chart": "Need at least 3 datasets to display radar chart",
    "# Performance Metrics面板": "# Performance metrics panel",
    "# 分类别详情": "# Per-category details",
    "### 分类别分析": "### Per-Category Analysis",
    " 详细分析": " Detailed Analysis",
    "# 分类别Accuracy": "# Per-category accuracy",
    "AI 裁判succeeded修正 ": "AI Judge successfully corrected ",
    " 误判样本！(这些样本已计入正确率)": " misjudged samples! (these are now included in the accuracy calculation)",
    "查看裁判修正详情": "View Judge Correction Details",
    "问题: ": "Question: ",
    "问题: (Prompt only)": "Question: (Prompt only)",
    "Model输出: ": "Model output: ",
    "Correct answer: ": "Correct answer: ",
    " | 提取预测(Error): ": " | Extracted prediction (wrong): ",
    "# Error分析": "# Error analysis",
    "# ExportOptions": "# Export options",
    "### ExportResult": "### Export Results",
    "under载汇总 CSV": "Download Summary CSV",
    "under载详细 JSON": "Download Detailed JSON",
    "Render多Model Comparison报告": "Render multi-model comparison report",
    "暂no对比Data": "No comparison data yet",
    "Model能力对比": "Model Capability Comparison",
    "# 收集所hasDataset": "# Collect all datasets",
    "# Build对比Data": "# Build comparison data",
    "# Display对比表": "# Display comparison table",
    "### Accuracy对比表": "### Accuracy Comparison Table",
    "# 对比Bar Chart": "# Comparison bar chart",
    "### Visualization对比": "### Visual Comparison",
    "各Modelinnot同DatasetonAccuracy对比": "Accuracy Comparison Across Models and Datasets",
    # Short common fragments (apply last due to ordering)
    "Display ": "Showing ",
}


def translate_file(filepath: str, translations: dict) -> tuple[int, list[str]]:
    """Apply translations to a single file. Returns (count, changes)."""
    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    original = content
    changes = []

    # Sort by length descending to avoid partial match collisions
    sorted_keys = sorted(translations.keys(), key=len, reverse=True)

    for cn_text in sorted_keys:
        en_text = translations[cn_text]
        if cn_text in content:
            count = content.count(cn_text)
            content = content.replace(cn_text, en_text)
            changes.append(f"  [{count}x] '{cn_text[:50]}...' → '{en_text[:50]}...'")

    if content != original:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    return len(changes), changes


def count_chinese(filepath: str) -> int:
    """Count Chinese character segments in a file."""
    with open(filepath, encoding="utf-8") as f:
        content = f.read()
    return len(re.findall(r"[\u4e00-\u9fff]+", content))


def main():
    target_files = [
        "ui/comparison_page.py",
        "ui/test_runner.py",
        "ui/dashboard_components.py",
        "ui/dataset_manager.py",
        "ui/thinking_components.py",
        "ui/log_viewer.py",
        "ui/export.py",
        "ui/history_browser.py",
        "ui/markdown_summary.py",
        "ui/evaluation_dashboard.py",
        "ui/quality_reports.py",
    ]

    print("=" * 60)
    print("Phase 5: Final Chinese → English translation sweep")
    print("=" * 60)

    total_changes = 0

    for fp in target_files:
        if not os.path.exists(fp):
            print(f"\n {fp} not found, skipping.")
            continue

        before = count_chinese(fp)
        n_changes, changes = translate_file(fp, TRANSLATIONS)
        after = count_chinese(fp)

        print(f"\n{fp}")
        print(
            f"   Before: {before} segments → After: {after} segments  ({n_changes} replacements)"
        )
        if changes:
            for c in changes[:5]:
                print(c)
            if len(changes) > 5:
                print(f"   ... and {len(changes) - 5} more")

        total_changes += n_changes

    print(f"\n{'=' * 60}")
    print(f"Total replacements: {total_changes}")
    print("=" * 60)

    # Summary
    print("\nFinal Chinese segment counts:")
    for fp in target_files:
        if os.path.exists(fp):
            remaining = count_chinese(fp)
            status = "[OK]" if remaining == 0 else "[WARN]"
            print(f"  {status} {fp}: {remaining}")


if __name__ == "__main__":
    main()
