[logger]
# 设置日志级别为 error，只显示错误
level = "error"

# 禁用消息日志
messageFormat = "%(message)s"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
fileWatcherType = "none"
